# Job Market Intelligence – Cumulative Exploratory Analysis

This notebook analyzes all cleaned offers stored in PostgreSQL. Each job ID appears once; the dataset grows as previously unseen offers are collected.

**Scope:** this is a cumulative collection, not a count of currently active vacancies, newly published jobs or hires. Retrieval timestamps are not publication dates. Normal scraping skips known URLs; targeted refreshes can replace stored values and timestamps.

## Running the analysis

1. Complete collection, cleaning and the database upsert first.
2. Start Docker and PostgreSQL, then run this notebook from top to bottom and enter the database password.
3. Review data-quality checks and collection coverage before interpreting results.
4. Numerical summaries recalculate on each run. Write reviewed, dated interpretation in separate monthly reports.
5. Preserve the August report separately. Filtering the current database by date does not freeze historical values.

This source notebook has cleared outputs to avoid mixing August results with updated code. Run all cells after each database update.

In [1]:
import re
from getpass import getpass
from html import escape

import pandas as pd
import plotly.express as px
from IPython.display import Markdown, display
from sqlalchemy import create_engine, URL, text
import plotly.io as pio

pio.renderers.default = "iframe"

# Read only: no database changes are made by this notebook.
db_url = URL.create(
    "postgresql+psycopg",
    username="analyst",
    password=getpass("PostgreSQL password: "),
    host="127.0.0.1",
    port=5432,
    database="job_market",
)
engine = create_engine(db_url)
try:
    with engine.connect() as connection:
        df = pd.read_sql_query(
            text("SELECT * FROM public.nofluff_it_jobs_clean ORDER BY scraped_at, job_id"),
            connection,
        )
finally:
    engine.dispose()

# Validation and reusable summaries
if df.empty:
    raise ValueError("No offers found. Run data preparation first.")
required_columns = {
    "job_id", "url", "title", "company", "company_size", "company_size_segment",
    "category", "experience", "experience_years_min", "workplace", "contract_type",
    "job_locations", "required_skills", "nice_to_have", "scraped_at", "salary_min",
    "salary_min_pln_monthly", "salary_max_pln_monthly", "salary_mid_pln_monthly",
    "salary_normalization_eligible", "salary_analysis_eligible",
}
missing_columns = required_columns - set(df.columns)
if missing_columns:
    raise ValueError(f"Missing columns: {sorted(missing_columns)}")
for key in ["job_id", "url"]:
    if df[key].isna().any() or df[key].astype(str).str.strip().eq("").any() or not df[key].is_unique:
        raise ValueError(f"{key} must be populated and unique.")
for flag in ["salary_normalization_eligible", "salary_analysis_eligible"]:
    if df[flag].isna().any() or not df[flag].isin([True, False]).all():
        raise ValueError(f"{flag} must contain non-null boolean values.")
    df[flag] = df[flag].astype(bool)
if (df["salary_analysis_eligible"] & ~df["salary_normalization_eligible"]).any():
    raise ValueError("Salary eligibility flags are inconsistent.")
for column in ["salary_min", "experience_years_min", "salary_min_pln_monthly",
               "salary_max_pln_monthly", "salary_mid_pln_monthly"]:
    df[column] = pd.to_numeric(df[column], errors="raise")
if df.loc[df["salary_analysis_eligible"], "salary_mid_pln_monthly"].isna().any():
    raise ValueError("Salary-eligible offers contain missing midpoints.")


def show_summary(*items):
    display(Markdown("### Calculated summary\n\n" + "\n".join(
        f"- {escape(str(item))}" for item in items
    )))


def distribution_summary(column, label):
    counts = df[column].dropna().value_counts()
    if counts.empty:
        return f"{label}: no reported values."
    leaders = counts[counts.eq(counts.max())]
    names = ", ".join(map(str, leaders.index))
    return (f"{label}: most frequent reported value(s): {names}; "
            f"{int(counts.max()):,} offers each ({counts.max()/len(df):.1%} of all offers). "
            f"Missing: {df[column].isna().sum():,}.")


def salary_summary(table, group, count="job_offers", median="median_salary"):
    valid = table.dropna(subset=[median])
    if valid.empty:
        return "No salary groups meet the comparison criteria."
    leaders = valid.loc[valid[median].eq(valid[median].max())]
    details = "; ".join(
        f"{row[group]}: PLN {row[median]:,.0f} (n={int(row[count]):,})"
        for _, row in leaders.iterrows()
    )
    return f"Highest median among included groups: {details}. Differences are descriptive."


print(f"Loaded {len(df):,} job offers with {df.shape[1]} columns from PostgreSQL.")

PostgreSQL password:  ········

Loaded 4,577 job offers with 38 columns from PostgreSQL.

## Analysis plan

The exploratory analysis focuses on six main questions:

1. What experience levels are most in demand?
2. What workplace models and contract types are most common?
3. Which job categories and companies show the highest recruitment activity?
4. How do salaries differ across experience levels, categories and employment conditions?
5. Which technologies and skills are most frequently required?
6. How are job opportunities and salaries distributed geographically?

## 1. Dataset overview

This section provides a high-level overview of the dataset, including the number
of job offers, companies, categories, salary availability, and data collection period.

In [2]:
# Convert scraping date to datetime
df["scraped_at"] = pd.to_datetime(
    df["scraped_at"],
    errors="coerce"
)

overview = pd.Series({
    "Job offers": len(df),
    "Unique companies": df["company"].nunique(),
    "Unique job titles": df["title"].nunique(),
    "Unique categories": df["category"].nunique(),
    "Offers with salary": df["salary_min"].notna().sum(),
    "Salary analysis eligible": df["salary_analysis_eligible"].sum(),
})

overview

Job offers                  4577
Unique companies             456
Unique job titles           3586
Unique categories             35
Offers with salary          3246
Salary analysis eligible    3223
dtype: int64

In [3]:
salary_available_pct = (
    df["salary_min"].notna().mean() * 100
)

salary_eligible_pct = (
    df["salary_analysis_eligible"].mean() * 100
)

print(
    f"Offers with salary: "
    f"{salary_available_pct:.1f}%"
)

print(
    f"Offers eligible for salary analysis: "
    f"{salary_eligible_pct:.1f}%"
)

print()
print(
    "Data collection period:",
    df["scraped_at"].min().date(),
    "to",
    df["scraped_at"].max().date()
)

Offers with salary: 70.9%
Offers eligible for salary analysis: 70.4%

Data collection period: 2026-08-24 to 2026-10-24

In [4]:
df[
    [
        "title",
        "company",
        "experience",
        "workplace",
        "salary_min",
        "salary_max"
    ]
].head()

,title,company,experience,workplace,salary_min,salary_max
0,1st Line Analyst with English,DCG,Junior,Remote,5900.0,6400.0
1,Administrator IT,iteo S.A.,Mid,None,10000.0,13000.0
2,Administrator/-ka Aplikacji Biznesowych - Depa...,T-Mobile Polska,Mid,Hybrid,NaN,NaN
3,ADMINISTRATOR SAP BASIS (k/m),MODIVO PLATFORM,Mid,Onsite,NaN,NaN
4,Administrator Systemów IT,Upvanta,Mid,None,500.0,650.0

In [5]:
show_summary(
    f"Cumulative collection: {len(df):,} offers from {df['company'].nunique():,} reported companies.",
    f"Salary normalization eligible: {df['salary_normalization_eligible'].sum():,} ({df['salary_normalization_eligible'].mean():.1%}).",
    f"Salary analysis eligible: {df['salary_analysis_eligible'].sum():,} ({df['salary_analysis_eligible'].mean():.1%}).",
    f"Normalized offers excluded by the quality flag: {(df['salary_normalization_eligible'] & ~df['salary_analysis_eligible']).sum():,}.",
)
collection_coverage = (
    df.dropna(subset=['scraped_at'])
    .assign(collection_month=lambda data: data['scraped_at'].dt.to_period('M').astype(str),
            collection_day=lambda data: data['scraped_at'].dt.date)
    .groupby('collection_month')
    .agg(stored_offers=('job_id', 'nunique'), observed_collection_days=('collection_day', 'nunique'),
         first_retrieval=('scraped_at', 'min'), last_retrieval=('scraped_at', 'max'))
)
display(collection_coverage)
print('Missing months are not zero-offer months. Observed collection days are not a complete run log.')

### Calculated summary

- Cumulative collection: 4,577 offers from 456 reported companies.
- Salary normalization eligible: 3,246 (70.9%).
- Salary analysis eligible: 3,223 (70.4%).
- Normalized offers excluded by the quality flag: 23.

,stored_offers,observed_collection_days,first_retrieval,last_retrieval
collection_month,,,,
2026-08,3360,2,2026-08-24 01:15:58,2026-08-26 00:16:20
2026-10,1217,1,2026-10-24 09:23:53,2026-10-24 10:39:10

Missing months are not zero-offer months. Observed collection days are not a complete run log.

## 2. Experience level

This section examines the distribution of job offers across different experience levels.

In [6]:
experience_counts = (
    df["experience"]
    .value_counts(dropna=False)
    .to_frame("job_offers")
)

experience_counts

            job_offers
experience
Senior            2451
Mid               1639
Expert             204
Junior             199
None                84

In [7]:
experience_summary = (
    df["experience"]
    .fillna("Missing")
    .value_counts()
    .rename_axis("experience")
    .reset_index(name="job_offers")
)

experience_summary["percentage"] = (
    experience_summary["job_offers"]
    / len(df)
    * 100
).round(1)

experience_summary

  experience  job_offers  percentage
0     Senior        2451        53.6
1        Mid        1639        35.8
2     Expert         204         4.5
3     Junior         199         4.3
4    Missing          84         1.8

In [8]:
df['experience_years_min'].describe()

count    2456.000000
mean        4.810261
std         2.049249
min         1.000000
25%         3.000000
50%         5.000000
75%         5.000000
max        15.000000
Name: experience_years_min, dtype: float64

In [9]:
experience_order = [
    "Senior",
    "Mid",
    "Junior",
    "Expert",
    "Missing",
]

experience_order += sorted(set(df["experience"].dropna()) - set(experience_order))

experience_summary = (
    df["experience"]
    .fillna("Missing")
    .value_counts()
    .reindex(
        experience_order,
        fill_value=0,
    )
    .rename_axis("experience")
    .reset_index(name="job_offers")
)

experience_summary["percentage"] = (
    experience_summary["job_offers"]
    / len(df)
    * 100
).round(1)

experience_summary["label"] = (
    experience_summary["job_offers"]
    .map(lambda value: f"{value:,}")
    + " ("
    + experience_summary["percentage"].map(
        lambda value: f"{value:.1f}%"
    )
    + ")"
)

fig = px.bar(
    experience_summary,
    x="job_offers",
    y="experience",
    orientation="h",
    text="label",
    category_orders={
        "experience": list(
            reversed(experience_order)
        )
    },
    title="Job Offers by Experience Level",
    labels={
        "job_offers": "Number of job offers",
        "experience": "Experience level",
    },
    color="experience",
    color_discrete_sequence=[
        "#3B6EA8",
        "#5A8AC6",
        "#72B7B2",
        "#F2CF5B",
        "#BAB0AC",
    ],
)

fig.update_traces(
    textposition="outside",
    cliponaxis=False,
    hovertemplate=(
        "<b>%{y}</b><br>"
        "Job offers: %{x:,}"
        "<extra></extra>"
    ),
)

fig.update_layout(
    width=1000,
    height=480,
    showlegend=False,
    plot_bgcolor="#F7F9FC",
    title=dict(
        x=0.02,
        xanchor="left",
    ),
    xaxis=dict(
        title="Number of job offers",
        range=[
            0,
            experience_summary["job_offers"].max() * 1.22,
        ],
        gridcolor="white",
        zeroline=False,
    ),
    yaxis=dict(
        title=None,
    ),
    margin=dict(
        l=100,
        r=140,
        t=80,
        b=60,
    ),
)

fig.show()

In [10]:
df.groupby('experience')['experience_years_min'].describe()

             count      mean       std  min  25%  50%  75%   max
experience
Expert       108.0  7.046296  2.396977  3.0  5.0  7.0  8.0  15.0
Junior        76.0  3.171053  2.317402  1.0  2.0  2.0  5.0  12.0
Mid          841.0  3.694411  1.728082  1.0  3.0  3.0  5.0  15.0
Senior      1404.0  5.359687  1.734181  1.0  5.0  5.0  6.0  15.0

In [11]:
experience_years = (
    df.groupby("experience")["experience_years_min"]
    .agg(
        job_offers="count",
        median_years="median",
        mean_years="mean"
    )
    .round(1)
)

experience_years

            job_offers  median_years  mean_years
experience
Expert             108           7.0         7.0
Junior              76           2.0         3.2
Mid                841           3.0         3.7
Senior            1404           5.0         5.4

In [12]:
experience_order = [
    "Junior",
    "Mid",
    "Senior",
    "Expert"
]

median_experience = (
    df.groupby("experience")["experience_years_min"]
    .median()
    .reindex(experience_order)
    .reset_index()
)

fig = px.bar(
    median_experience,
    x="experience",
    y="experience_years_min",
    text="experience_years_min",
    title="Median Required Years of Experience by Experience Level",
    labels={
        "experience": "Experience level",
        "experience_years_min": "Median required years"
    }
)

fig.update_traces(
    textposition="outside"
)

fig.update_layout(
    showlegend=False,
    yaxis_title="Median required years of experience",
    xaxis_title="Experience level"
)

fig.update_yaxes(
    rangemode="tozero"
)

fig.show()

## 3. Workplace Models

This section examines the distribution of remote, hybrid and onsite job offers and compares workplace models across experience levels.

In [13]:
workplace_summary = (
    df["workplace"]
    .fillna("Missing")
    .value_counts()
    .rename_axis("workplace")
    .reset_index(name="job_offers")
)

workplace_summary["percentage"] = (
    workplace_summary["job_offers"]
    / len(df)
    * 100
).round(1)

workplace_summary

  workplace  job_offers  percentage
0    Hybrid        2535        55.4
1    Remote        1244        27.2
2   Missing         787        17.2
3    Onsite          11         0.2

In [14]:
fig = px.pie(
    workplace_summary,
    names="workplace",
    values="job_offers",
    hole=0.5,
    title="Distribution of Workplace Models"
)

fig.update_traces(
    textinfo="percent+label",
    insidetextorientation="horizontal"
)

fig.show()

In [15]:
workplace_experience = (
    pd.crosstab(
        df["experience"],
        df["workplace"].fillna("Missing"),
        normalize="index"
    )
    * 100
).round(1)

workplace_experience

workplace   Hybrid  Missing  Onsite  Remote
experience
Expert        60.8     15.2     0.0    24.0
Junior        65.8     19.1     0.0    15.1
Mid           57.2     20.0     0.6    22.2
Senior        52.9     14.6     0.0    32.5

In [16]:
workplace_experience_plot = (
    workplace_experience
    .reset_index()
    .melt(
        id_vars="experience",
        var_name="workplace",
        value_name="percentage"
    )
)

In [17]:
fig = px.bar(
    workplace_experience_plot,
    x="experience",
    y="percentage",
    color="workplace",
    text="percentage",
    barmode="group",
    category_orders={
        "experience": [
            "Junior",
            "Mid",
            "Senior",
            "Expert"
        ]
    },
    title="Workplace Model Distribution by Experience Level",
    labels={
        "experience": "Experience level",
        "percentage": "Share of job offers (%)",
        "workplace": "Workplace model"
    }
)

fig.update_traces(
    texttemplate="%{text:.1f}%",
    textposition="outside"
)

fig.update_layout(
    yaxis_ticksuffix="%"
)

fig.show()

In [18]:
show_summary(distribution_summary('experience', 'Experience'),
    distribution_summary('workplace', 'Workplace'),
    f"Senior and Mid combined: {df['experience'].isin(['Senior', 'Mid']).mean():.1%} of all offers.",
    "Within-experience charts exclude missing experience; missing workplace is retained.")

### Calculated summary

- Experience: most frequent reported value(s): Senior; 2,451 offers each (53.6% of all offers). Missing: 84.
- Workplace: most frequent reported value(s): Hybrid; 2,535 offers each (55.4% of all offers). Missing: 787.
- Senior and Mid combined: 89.4% of all offers.
- Within-experience charts exclude missing experience; missing workplace is retained.

## 4. Job categories

This section examines recruitment activity and experience-level composition across the standardized job categories.

In [19]:
category_summary = (
    df["category"]
    .fillna("Missing")
    .value_counts()
    .rename_axis("category")
    .reset_index(name="job_offers")
)

category_summary.head(20)

                 category  job_offers
0                 Backend         802
1                    Data         520
2                 Testing         396
3               Fullstack         374
4                  DevOps         369
5                      AI         253
6                     ERP         242
7         Project Manager         241
8                Security         235
9            Architecture         174
10                Support         170
11               Frontend         109
12     Product Management         103
13      Business Analysis          88
14               Embedded          82
15                 Mobile          72
16                Inne IT          69
17     Sys. Administrator          58
18                 Design          53
19  Business Intelligence          30

In [20]:
top_10_categories = (
    category_summary
    .head(10)
    .sort_values(
        "job_offers",
        ascending=True,
    )
)

fig = px.bar(
    top_10_categories,
    x="job_offers",
    y="category",
    orientation="h",
    text="job_offers",
    title="Top 10 Job Categories",
    labels={
        "job_offers": "Number of job offers",
        "category": "Job category",
    },
)

fig.update_traces(textposition="outside")
fig.update_layout(showlegend=False)
fig.show()

In [21]:
top_10_category_names = (
    category_summary
    .head(10)["category"]
    .tolist()
)

category_experience_df = (
    df.loc[
        df["category"].isin(top_10_category_names),
        ["job_id", "category", "experience"],
    ]
    .dropna(subset=["experience"])
)

In [22]:
category_experience = (
    pd.crosstab(
        category_experience_df["category"],
        category_experience_df["experience"],
        normalize="index"
    )
    * 100
).round(1)

category_experience = (
    category_experience
    .reindex(
        index=top_10_category_names,
        columns=[
            "Junior",
            "Mid",
            "Senior",
            "Expert"
        ],
        fill_value=0
    )
)

category_experience

experience       Junior   Mid  Senior  Expert
category
Backend             5.1  28.6    62.8     3.4
Data                3.7  34.0    56.4     6.0
Testing             5.2  43.1    49.9     1.8
Fullstack           2.2  35.8    59.9     2.2
DevOps              1.9  32.7    61.3     4.1
AI                  2.8  30.2    59.7     7.3
ERP                 2.1  39.8    51.3     6.8
Project Manager     3.4  35.9    55.1     5.6
Security            2.6  45.7    43.5     8.3
Architecture        1.2  26.6    55.5    16.8

In [23]:
fig = px.imshow(
    category_experience,
    text_auto=".1f",
    aspect="auto",
    title="Experience Level Distribution by Job Category",
    labels={
        "x": "Experience level",
        "y": "Job category",
        "color": "Share of offers (%)"
    }
)

fig.show()

In [24]:
show_summary(distribution_summary('category', 'Category'),
    "Category experience percentages use offers with known experience within each selected category.")

### Calculated summary

- Category: most frequent reported value(s): Backend; 802 offers each (17.5% of all offers). Missing: 0.
- Category experience percentages use offers with known experience within each selected category.

## 5. Contract types

This section examines the distribution of employment contract types across job offers.

The initial analysis uses the original contract values, including offers that provide multiple contract options. Missing contract information is also included to show the completeness of the data.

In [25]:
df['contract_type'].unique()

array([None, 'B2B', 'B2B, Umowa o pracę', 'Umowa o pracę',
       'B2B, Umowa zlecenie', 'Umowa zlecenie',
       'Umowa o pracę, Umowa zlecenie',
       'B2B, Umowa o pracę, Umowa zlecenie', 'Umowa o dzieło'],
      dtype=object)

In [26]:
contract_type_summary = (
    df["contract_type"]
    .fillna("Missing")
    .value_counts()
    .rename_axis("contract_type")
    .reset_index(name="job_offers")
)

contract_type_summary["percentage"] = (
    contract_type_summary["job_offers"]
    / len(df)
    * 100
).round(1)

contract_type_summary

                        contract_type  job_offers  percentage
0                                 B2B        3143        68.7
1                             Missing        1013        22.1
2                  B2B, Umowa o pracę         231         5.0
3                       Umowa o pracę         182         4.0
4                      Umowa zlecenie           4         0.1
5                 B2B, Umowa zlecenie           1         0.0
6       Umowa o pracę, Umowa zlecenie           1         0.0
7  B2B, Umowa o pracę, Umowa zlecenie           1         0.0
8                      Umowa o dzieło           1         0.0

In [27]:
contract_type_plot = (
    contract_type_summary
    .sort_values(
        "job_offers",
        ascending=True
    )
)

fig = px.bar(
    contract_type_plot,
    x="job_offers",
    y="contract_type",
    orientation="h",
    text="job_offers",
    title="Distribution of Contract Types",
    labels={
        "job_offers": "Number of job offers",
        "contract_type": "Contract type"
    }
)

fig.update_traces(
    textposition="outside"
)

fig.update_layout(
    showlegend=False
)

fig.show()

In [28]:
experience_order = [
    "Junior",
    "Mid",
    "Senior",
    "Expert"
]

contract_experience = (
    pd.crosstab(
        df["experience"],
        df["contract_type"].fillna("Missing"),
        normalize="index"
    )
    * 100
).round(1)

contract_experience = (
    contract_experience
    .reindex(experience_order)
)

contract_experience

contract_type,B2B,"B2B, Umowa o pracę","B2B, Umowa o pracę, Umowa zlecenie","B2B, Umowa zlecenie",Missing,Umowa o dzieło,Umowa o pracę,"Umowa o pracę, Umowa zlecenie",Umowa zlecenie
experience,,,,,,,,,
Junior,42.2,6.5,0.0,0.0,39.2,0.5,9.5,0.5,1.5
Mid,69.9,6.2,0.1,0.1,19.8,0.0,4.0,0.0,0.0
Senior,71.6,4.4,0.0,0.0,20.6,0.0,3.4,0.0,0.0
Expert,62.7,4.9,0.0,0.0,28.4,0.0,3.9,0.0,0.0

In [29]:
main_contract_types = [
    "B2B",
    "B2B, Umowa o pracę",
    "Umowa o pracę",
    "Missing"
]

contract_experience_plot = (
    contract_experience.reindex(columns=main_contract_types, fill_value=0)
    .reset_index()
    .melt(
        id_vars="experience",
        var_name="contract_type",
        value_name="percentage"
    )
)

fig = px.bar(
    contract_experience_plot,
    x="experience",
    y="percentage",
    color="contract_type",
    barmode="group",
    text="percentage",
    category_orders={
        "experience": [
            "Junior",
            "Mid",
            "Senior",
            "Expert"
        ]
    },
    title="Contract Type by Experience Level",
    labels={
        "experience": "Experience level",
        "percentage": "Share of job offers (%)",
        "contract_type": "Contract type"
    }
)

fig.update_traces(
    texttemplate="%{text:.1f}%",
    textposition="outside"
)

fig.show()

In [30]:
show_summary(distribution_summary('contract_type', 'Contract options'),
    "Contract combinations are separate groups. Missing contract information is not evidence of a particular contract type.")

### Calculated summary

- Contract options: most frequent reported value(s): B2B; 3,143 offers each (68.7% of all offers). Missing: 1,013.
- Contract combinations are separate groups. Missing contract information is not evidence of a particular contract type.

## 6. Company Analysis

This section examines company-level recruitment activity, market concentration and differences between company-size segments.

### Company Data Quality

In [31]:
company_overview = pd.Series({
    "Job offers": len(df),
    "Company available": df["company"].notna().sum(),
    "Company missing": df["company"].isna().sum(),
    "Unique company names": df["company"].nunique(),
    "Company size available (%)": (
        df["company_size"].notna().mean() * 100
    ),
}).round(1)

company_overview

Job offers                    4577.0
Company available             4577.0
Company missing                  0.0
Unique company names           456.0
Company size available (%)      74.2
dtype: float64

In [32]:
df["company"].value_counts().head(10)

company
Antal                          252
Scalo                          250
Mindbox Sp. z o.o.             231
Link Group                     212
Upvanta                        142
Square One Resources           133
GFT Poland                     117
Ework Group                    105
ITFS Sp. z o.o.                 97
Capgemini Polska Sp. z o.o.     93
Name: count, dtype: int64

### Companies with the Highest Recruitment Activity

The ranking shows the number of unique offers published by each company. It represents job-posting activity on No Fluff Jobs rather than the total employment scale of an organization.

In [33]:
company_ranking = (
    df.dropna(subset=["company"])
    .groupby("company")
    .agg(
        job_offers=("job_id", "nunique")
    )
    .sort_values(
        "job_offers",
        ascending=False,
    )
)

company_ranking.head(10)

                             job_offers
company
Antal                               252
Scalo                               250
Mindbox Sp. z o.o.                  231
Link Group                          212
Upvanta                             142
Square One Resources                133
GFT Poland                          117
Ework Group                         105
ITFS Sp. z o.o.                      97
Capgemini Polska Sp. z o.o.          93

In [34]:
top_10_companies = (
    company_ranking
    .head(10)
    .sort_values(
        "job_offers",
        ascending=True,
    )
    .reset_index()
)

top_10_companies

                       company  job_offers
0  Capgemini Polska Sp. z o.o.          93
1              ITFS Sp. z o.o.          97
2                  Ework Group         105
3                   GFT Poland         117
4         Square One Resources         133
5                      Upvanta         142
6                   Link Group         212
7           Mindbox Sp. z o.o.         231
8                        Scalo         250
9                        Antal         252

In [35]:

fig = px.bar(
    top_10_companies,
    x="job_offers",
    y="company",
    orientation="h",
    text="job_offers",
    title=(
        "Companies with the Highest Number "
        "of Published Job Offers"
    ),
    labels={
        "job_offers": "Number of job offers",
        "company": "Company",
    },
)

fig.update_traces(
    textposition="outside"
)

fig.update_layout(
    yaxis_title=None,
    showlegend=False,
    margin=dict(
        l=20,
        r=60,
        t=70,
        b=40,
    ),
)

fig.show()

In [36]:
company_offer_counts = (
    df.dropna(subset=["company"])
    .groupby("company")["job_id"]
    .nunique()
    .sort_values(ascending=False)
)

total_companies = company_offer_counts.size
total_offers_with_company = company_offer_counts.sum()

top_10_offers = company_offer_counts.head(10).sum()
top_20_offers = company_offer_counts.head(20).sum()

top_10_share = (
    top_10_offers
    / total_offers_with_company
    * 100
)

top_20_share = (
    top_20_offers
    / total_offers_with_company
    * 100
)

single_offer_companies = (
    company_offer_counts == 1
).sum()

single_offer_company_share = (
    single_offer_companies
    / total_companies
    * 100
)

median_offers_per_company = (
    company_offer_counts.median()
)

In [37]:
market_concentration = pd.DataFrame({
    "metric": [
        "Companies",
        "Offers with identified company",
        "Offers from Top 10 companies",
        "Offers from Top 10 companies (%)",
        "Offers from Top 20 companies",
        "Offers from Top 20 companies (%)",
        "Companies with one offer",
        "Companies with one offer (%)",
        "Median offers per company",
    ],
    "value": [
        total_companies,
        total_offers_with_company,
        top_10_offers,
        round(top_10_share, 1),
        top_20_offers,
        round(top_20_share, 1),
        single_offer_companies,
        round(single_offer_company_share, 1),
        median_offers_per_company,
    ],
})

market_concentration

                             metric   value
0                         Companies   456.0
1    Offers with identified company  4577.0
2      Offers from Top 10 companies  1632.0
3  Offers from Top 10 companies (%)    35.7
4      Offers from Top 20 companies  2471.0
5  Offers from Top 20 companies (%)    54.0
6          Companies with one offer   187.0
7      Companies with one offer (%)    41.0
8         Median offers per company     2.0

In [38]:
show_summary(f"Top 10 companies: {top_10_share:.1f}% of offers with an identified company.",
    f"Top 20 companies: {top_20_share:.1f}% of offers with an identified company.",
    f"Companies with one offer: {single_offer_company_share:.1f}%; median offers per company: {median_offers_per_company:g}.",
    "These are collected listing counts, not employer market shares.")

### Calculated summary

- Top 10 companies: 35.7% of offers with an identified company.
- Top 20 companies: 54.0% of offers with an identified company.
- Companies with one offer: 41.0%; median offers per company: 2.
- These are collected listing counts, not employer market shares.

### Company Size Distribution

This section examines which company-size segments publish the most job offers. Company-size segments are based on the reported lower employee-count boundary.

In [39]:
company_size_order = [
    "Small",
    "Medium",
    "Large",
    "Enterprise",
    "Missing",
]

company_size_summary = (
    df["company_size_segment"]
    .value_counts()
    .reindex(
        company_size_order,
        fill_value=0,
    )
    .rename_axis("company_size_segment")
    .reset_index(name="job_offers")
)

company_size_summary["percentage"] = (
    company_size_summary["job_offers"]
    / len(df)
    * 100
).round(1)

company_size_summary

  company_size_segment  job_offers  percentage
0                Small         253         5.5
1               Medium         713        15.6
2                Large        1298        28.4
3           Enterprise        1133        24.8
4              Missing        1180        25.8

In [40]:
company_size_colors = {
    "Small": "#4C78A8",
    "Medium": "#72B7B2",
    "Large": "#F2CF5B",
    "Enterprise": "#F58518",
    "Missing": "#BAB0AC",
}

fig = px.pie(
    company_size_summary,
    names="company_size_segment",
    values="job_offers",
    hole=0.5,
    title="Distribution of Job Offers by Company Size",
    color="company_size_segment",
    color_discrete_map=company_size_colors,
    category_orders={
        "company_size_segment": company_size_order,
    },
)

fig.update_traces(
    textinfo="percent+label",
    textposition="outside",
    hovertemplate=(
        "<b>%{label}</b><br>"
        "Job offers: %{value}<br>"
        "Share: %{percent}"
        "<extra></extra>"
    ),
)

fig.update_layout(
    showlegend=True,
    legend_title_text="Company size",
    margin=dict(
        l=40,
        r=40,
        t=70,
        b=40,
    ),
)

fig.show()

In [41]:
company_size_order = [
    "Small",
    "Medium",
    "Large",
    "Enterprise",
]

### Company Size by Experience Level

This section compares the experience-level distribution within each company-size segment.

> Are smaller companies more likely to hire experienced candidates than larger organizations?

In [42]:
experience_order = [
    "Junior",
    "Mid",
    "Senior",
    "Expert",
    "Missing",
]

company_experience_df = (
    df.loc[
        df["company_size_segment"].isin(
            company_size_order
        )
    ]
    .assign(
        experience=lambda data:
            data["experience"].fillna("Missing")
    )
)

In [43]:
company_experience = (
    pd.crosstab(
        company_experience_df["company_size_segment"],
        company_experience_df["experience"],
        normalize="index",
    )
    .mul(100)
    .round(1)
    .reindex(
        index=company_size_order,
        columns=experience_order,
        fill_value=0,
    )
)

company_experience

experience            Junior   Mid  Senior  Expert  Missing
company_size_segment
Small                    6.3  28.5    60.1     4.3      0.8
Medium                   3.1  50.1    43.5     2.9      0.4
Large                    2.1  36.1    56.7     4.4      0.8
Enterprise               6.4  30.3    54.9     5.6      2.7

In [44]:
company_experience_plot = (
    company_experience
    .reset_index()
    .melt(
        id_vars="company_size_segment",
        var_name="experience",
        value_name="percentage",
    )
)

In [45]:
fig = px.imshow(
    company_experience,
    text_auto=".1f",
    aspect="auto",
    color_continuous_scale="Blues",
    title="Experience Level Distribution by Company Size",
    labels={
        "x": "Experience level",
        "y": "Company size",
        "color": "Share of offers (%)",
    },
)

fig.update_traces(
    texttemplate="%{z:.1f}%",
    hovertemplate=(
        "Company size: %{y}<br>"
        "Experience: %{x}<br>"
        "Share: %{z:.1f}%"
        "<extra></extra>"
    ),
)

fig.update_layout(
    height=450,
    xaxis_side="bottom",
    coloraxis_colorbar=dict(
        title="Share (%)",
        ticksuffix="%",
    ),
)

fig.show()

### Company Size by Workplace Model

This section examines how remote, hybrid and onsite work arrangements differ across company-size segments.

> Which company sizes offer the greatest workplace flexibility?

In [46]:
workplace_order = [
    "Remote",
    "Hybrid",
    "Onsite",
    "Missing",
]

company_workplace_df = (
    df.loc[
        df["company_size_segment"].isin(
            company_size_order
        )
    ]
    .assign(
        workplace=lambda data:
            data["workplace"].fillna("Missing")
    )
)

In [47]:
company_workplace = (
    pd.crosstab(
        company_workplace_df["company_size_segment"],
        company_workplace_df["workplace"],
        normalize="index",
    )
    .mul(100)
    .round(1)
    .reindex(
        index=company_size_order,
        columns=workplace_order,
        fill_value=0,
    )
)

company_workplace

workplace             Remote  Hybrid  Onsite  Missing
company_size_segment
Small                   49.0    26.5     0.8     23.7
Medium                  35.5    39.6     0.1     24.8
Large                   29.2    54.2     0.0     16.6
Enterprise              14.1    73.9     0.0     12.0

In [48]:
company_workplace_plot = (
    company_workplace
    .reset_index()
    .melt(
        id_vars="company_size_segment",
        var_name="workplace",
        value_name="percentage",
    )
)

In [49]:
workplace_order = [
    "Remote",
    "Hybrid",
    "Onsite",
    "Missing",
]

workplace_colors = {
    "Remote": "#4C78A8",
    "Hybrid": "#72B7B2",
    "Onsite": "#F58518",
    "Missing": "#BAB0AC",
}

company_workplace_plot["label"] = (
    company_workplace_plot["percentage"]
    .apply(lambda value: f"{value:.1f}%")
)

fig = px.bar(
    company_workplace_plot,
    x="company_size_segment",
    y="percentage",
    color="workplace",
    text="label",
    barmode="group",
    category_orders={
        "company_size_segment": company_size_order,
        "workplace": workplace_order,
    },
    color_discrete_map=workplace_colors,
    title="Workplace Model Distribution by Company Size",
    labels={
        "company_size_segment": "Company size",
        "percentage": "Share of job offers (%)",
        "workplace": "Workplace model",
    },
)

fig.update_traces(
    texttemplate="%{text}",
    textposition="outside",
    cliponaxis=False,
    hovertemplate=(
        "<b>%{fullData.name}</b><br>"
        "Company size: %{x}<br>"
        "Share: %{y:.1f}%"
        "<extra></extra>"
    ),
)

fig.update_layout(
    width=1050,
    height=550,
    bargap=0.15,
    bargroupgap=0.05,
    yaxis=dict(
        title="Share of job offers",
        ticksuffix="%",
        range=[
            0,
            company_workplace_plot["percentage"].max() + 10,
        ],
    ),
    xaxis=dict(
        title="Company size",
        categoryorder="array",
        categoryarray=company_size_order,
    ),
    legend=dict(
        title="Workplace model",
        orientation="h",
        yanchor="bottom",
        y=1.02,
        xanchor="center",
        x=0.5,
    ),
    uniformtext_minsize=8,
    uniformtext_mode="show",
    margin=dict(
        l=70,
        r=40,
        t=120,
        b=70,
    ),
)

fig.show()

### Company Size by Contract Type

This section compares the most common contract options across company-size segments. Contract combinations are preserved because a single job offer may provide more than one employment option.

In [50]:
main_contract_mapping = {
    "B2B": "B2B",
    "Umowa o pracę": "UoP",
    "B2B, Umowa o pracę": "B2B + UoP",
}

df["contract_group"] = (
    df["contract_type"]
    .map(main_contract_mapping)
)

df["contract_group"] = (
    df["contract_group"]
    .where(
        df["contract_type"].isna()
        | df["contract_group"].notna(),
        "Other",
    )
    .fillna("Missing")
)

In [51]:
contract_order = [
    "B2B",
    "UoP",
    "B2B + UoP",
    "Other",
    "Missing",
]

In [52]:
company_contract_df = (
    df.loc[
        df["company_size_segment"].isin(
            company_size_order
        )
    ]
)

company_contract = (
    pd.crosstab(
        company_contract_df["company_size_segment"],
        company_contract_df["contract_group"],
        normalize="index",
    )
    .mul(100)
    .round(1)
    .reindex(
        index=company_size_order,
        columns=contract_order,
        fill_value=0,
    )
)

company_contract

contract_group         B2B  UoP  B2B + UoP  Other  Missing
company_size_segment
Small                 85.0  2.0        1.6    0.4     11.1
Medium                79.8  2.9        2.4    0.3     14.6
Large                 84.3  3.7        0.5    0.2     11.3
Enterprise            45.5  4.2        0.5    0.1     49.6

In [53]:
company_contract_plot = (
    company_contract
    .reset_index()
    .melt(
        id_vars="company_size_segment",
        var_name="contract_group",
        value_name="percentage",
    )
)

In [54]:
contract_order = [
    "B2B",
    "UoP",
    "B2B + UoP",
    "Other",
    "Missing",
]

contract_colors = {
    "B2B": "#3B6EA8",
    "UoP": "#F28E2B",
    "B2B + UoP": "#59A6A6",
    "Other": "#AF7AA1",
    "Missing": "#B8B0AD",
}

company_contract_plot["label"] = (
    company_contract_plot["percentage"]
    .apply(lambda value: f"{value:.1f}%")
)

fig = px.bar(
    company_contract_plot,
    x="percentage",
    y="company_size_segment",
    color="contract_group",
    text="label",
    orientation="h",
    barmode="group",
    category_orders={
        "company_size_segment": company_size_order,
        "contract_group": contract_order,
    },
    color_discrete_map=contract_colors,
    title="Contract Type Distribution by Company Size",
    labels={
        "company_size_segment": "Company size",
        "percentage": "Share of job offers (%)",
        "contract_group": "Contract type",
    },
)

fig.update_traces(
    texttemplate="%{text}",
    textposition="outside",
    cliponaxis=False,
    hovertemplate=(
        "<b>%{fullData.name}</b><br>"
        "Company size: %{y}<br>"
        "Share of offers: %{x:.1f}%"
        "<extra></extra>"
    ),
)

fig.update_layout(
    width=1200,
    height=700,
    bargap=0.22,
    bargroupgap=0.06,
    plot_bgcolor="#F7F9FC",
    paper_bgcolor="white",
    title=dict(
        x=0.02,
        xanchor="left",
        font=dict(size=20),
    ),
    xaxis=dict(
        title="Share of job offers",
        range=[0, 100],
        tickmode="linear",
        tick0=0,
        dtick=10,
        ticksuffix="%",
        gridcolor="white",
        zeroline=False,
    ),
    yaxis=dict(
        title="Company size",
        categoryorder="array",
        categoryarray=list(
            reversed(company_size_order)
        ),
    ),
    legend=dict(
        title=None,
        orientation="h",
        yanchor="bottom",
        y=1.02,
        xanchor="center",
        x=0.5,
    ),
    uniformtext_minsize=8,
    uniformtext_mode="show",
    margin=dict(
        l=110,
        r=70,
        t=120,
        b=70,
    ),
)

fig.show()

In [55]:
show_summary(distribution_summary('company_size_segment', 'Company size'),
    f"Unknown size segment: {df['company_size_segment'].fillna('Missing').eq('Missing').mean():.1%} of offers.",
    "Segments use the reported lower employee-count bound; size comparisons are descriptive.")

### Calculated summary

- Company size: most frequent reported value(s): Large; 1,298 offers each (28.4% of all offers). Missing: 0.
- Unknown size segment: 25.8% of offers.
- Segments use the reported lower employee-count bound; size comparisons are descriptive.

### Profile of the Most Active Companies

This table summarizes the recruitment profiles of the ten companies with the highest number of published job offers.

In [56]:
def most_common_value(series):
    values = series.dropna()

    if values.empty:
        return "Missing"

    return values.mode().iloc[0]

In [57]:
top_company_names = (
    df.dropna(subset=["company"])
    .groupby("company")["job_id"]
    .nunique()
    .nlargest(10)
    .index
)

In [58]:
top_company_profiles = (
    df[df["company"].isin(top_company_names)]
    .groupby("company")
    .agg(
        job_offers=("job_id", "nunique"),
        dominant_category=(
            "category",
            most_common_value,
        ),
        dominant_experience=(
            "experience",
            most_common_value,
        ),
        dominant_workplace=(
            "workplace",
            most_common_value,
        ),
        dominant_company_size=(
            "company_size_segment",
            most_common_value,
        ),
    )
    .sort_values(
        "job_offers",
        ascending=False,
    )
    .reset_index()
)

top_company_profiles

,company,job_offers,dominant_category,dominant_experience,dominant_workplace,dominant_company_size
0,Antal,252,Data,Mid,Hybrid,Medium
1,Scalo,250,Data,Senior,Hybrid,Large
2,Mindbox Sp. z o.o.,231,Backend,Senior,Hybrid,Missing
3,Link Group,212,Backend,Senior,Remote,Large
4,Upvanta,142,Backend,Mid,Remote,Missing
5,Square One Resources,133,Data,Senior,Remote,Small
6,GFT Poland,117,DevOps,Senior,Hybrid,Enterprise
7,Ework Group,105,Testing,Senior,Hybrid,Large
8,ITFS Sp. z o.o.,97,Testing,Mid,Remote,Large
9,Capgemini Polska Sp. z o.o.,93,Support,Senior,Hybrid,Enterprise

In [59]:
show_summary(distribution_summary('company', 'Company'),
    "Recruiters and outsourcing firms may represent several clients; counts do not measure internal company growth.")

### Calculated summary

- Company: most frequent reported value(s): Antal; 252 offers each (5.5% of all offers). Missing: 0.
- Recruiters and outsourcing firms may represent several clients; counts do not measure internal company growth.

## 7. Salary analysis

This section compares standardized monthly salary ranges in PLN. Medians and quartiles are preferred because salary distributions are right-skewed.

### 7.1 Analysis scope and salary distribution

Begin with all records that can be normalized by currency and salary period, then use the quality flag prepared during data cleaning to exclude implausible salary values.

In [60]:
salary_df = df.loc[
    df["salary_normalization_eligible"]
].copy()

print("All offers:", len(df))
print("Offers eligible for normalization:", len(salary_df))

salary_df[
    [
        "salary_min_pln_monthly",
        "salary_max_pln_monthly",
        "salary_mid_pln_monthly",
    ]
].describe().round(2)

All offers: 4577
Offers eligible for normalization: 3246

       salary_min_pln_monthly  salary_max_pln_monthly  salary_mid_pln_monthly
count                 3246.00                 3246.00                 3246.00
mean                 22059.65                27388.61                24724.13
std                  20018.57                33002.93                26437.12
min                     90.00                  110.00                  100.00
25%                  17500.00                21840.00                20100.00
50%                  21840.00                26880.00                24150.00
75%                  26000.00                31500.00                28560.00
max                1092000.00              1848000.00              1470000.00

In [61]:
salary_df = df.loc[
    df["salary_analysis_eligible"]
].copy()

print("Eligible before quality filter:", df["salary_normalization_eligible"].sum())
print("Included after quality filter:", len(salary_df))
print(
    "Excluded as implausible:",
    df["salary_normalization_eligible"].sum() - len(salary_df),
)

Eligible before quality filter: 3246
Included after quality filter: 3223
Excluded as implausible: 23

### Salary analysis scope

Salary records were standardized to approximate monthly PLN values.
Offers with a midpoint below PLN 5,000 or above PLN 100,000 were excluded
from salary comparisons as implausible source-data values.

The records remain in the cleaned dataset and are excluded only from
salary-related analysis.

In [62]:
fig = px.histogram(
    salary_df,
    x="salary_mid_pln_monthly",
    nbins=40,
    title="Distribution of Monthly Salary Midpoints",
    labels={
        "salary_mid_pln_monthly":
            "Monthly salary midpoint (PLN)"
    },
)

fig.update_layout(
    yaxis_title="Number of job offers",
    showlegend=False,
)

fig.show()

In [63]:
values = salary_df['salary_mid_pln_monthly'].dropna()
if values.empty:
    show_summary("No offers are eligible for salary analysis.")
else:
    show_summary(f"Salary analysis includes {len(values):,} offers.",
        f"Median monthly midpoint: PLN {values.median():,.0f}.",
        f"Middle 50%: PLN {values.quantile(.25):,.0f} to PLN {values.quantile(.75):,.0f}.",
        "These are advertised salary-range midpoints, not observed employee earnings.")

### Calculated summary

- Salary analysis includes 3,223 offers.
- Median monthly midpoint: PLN 24,311.
- Middle 50%: PLN 20,160 to PLN 28,560.
- These are advertised salary-range midpoints, not observed employee earnings.

### 7.2 Salary by experience level

Compare medians and the middle 50% of salary ranges across standardized experience levels.

In [64]:
salary_by_experience = (
    salary_df
    .dropna(subset=["experience"])
    .groupby(
        "experience",
        observed=True,
    )
    .agg(
        job_offers=("job_id", "nunique"),
        median_salary=("salary_mid_pln_monthly", "median"),
        q1_salary=("salary_mid_pln_monthly", lambda x: x.quantile(0.25)),
        q3_salary=("salary_mid_pln_monthly", lambda x: x.quantile(0.75)),
    )
    .round(0)
    .reset_index()
)

experience_order = [
    "Junior",
    "Mid",
    "Senior",
    "Expert",
]

salary_by_experience["experience"] = pd.Categorical(
    salary_by_experience["experience"],
    categories=experience_order,
    ordered=True,
)

salary_by_experience = (
    salary_by_experience
    .sort_values("experience")
)

In [65]:
junior_values = salary_by_experience.loc[
    salary_by_experience['experience'].eq('Junior'), 'median_salary'
].dropna()
junior_median = junior_values.iloc[0] if not junior_values.empty else float('nan')
salary_by_experience['salary_premium_vs_junior_pct'] = (
    (salary_by_experience['median_salary'] / junior_median - 1) * 100
).round(1) if junior_median > 0 else float('nan')
salary_by_experience

,experience,job_offers,median_salary,q1_salary,q3_salary,salary_premium_vs_junior_pct
1,Junior,121,13225.0,8925.0,18816.0,0.0
2,Mid,1079,21000.0,16800.0,25357.0,58.8
3,Senior,1849,25200.0,22500.0,29400.0,90.5
0,Expert,144,30240.0,26678.0,32970.0,128.7

In [66]:
fig = px.box(
    salary_df.dropna(subset=["experience"]),
    x="experience",
    y="salary_mid_pln_monthly",
    category_orders={
        "experience": experience_order,
    },
    points=False,
    title="Monthly Salary Distribution by Experience Level",
    labels={
        "experience": "Experience level",
        "salary_mid_pln_monthly":
            "Monthly salary midpoint (PLN)",
    },
)

fig.update_layout(
    showlegend=False,
    height=550,
)

fig.show()

In [67]:
show_summary(salary_summary(salary_by_experience, 'experience'),
    "Review group sizes and quartiles. Junior-relative percentages are unavailable without a valid Junior baseline.")

### Calculated summary

- Highest median among included groups: Expert: PLN 30,240 (n=144). Differences are descriptive.
- Review group sizes and quartiles. Junior-relative percentages are unavailable without a valid Junior baseline.

### 7.3 Salary by job category

Compare categories with at least 30 salary observations, then repeat the comparison for Senior roles to partially control for experience composition.

In [68]:
salary_by_category = (
    salary_df
    .dropna(subset=["category"])
    .groupby("category")
    .agg(
        job_offers=("job_id", "nunique"),
        median_salary=("salary_mid_pln_monthly", "median"),
        q1_salary=("salary_mid_pln_monthly", lambda x: x.quantile(0.25)),
        q3_salary=("salary_mid_pln_monthly", lambda x: x.quantile(0.75)),
    )
    .reset_index()
)

salary_by_category = (
    salary_by_category
    .query("job_offers >= 30")
    .sort_values("median_salary")
)

salary_by_category[
    [
        "median_salary",
        "q1_salary",
        "q3_salary",
    ]
] = salary_by_category[
    [
        "median_salary",
        "q1_salary",
        "q3_salary",
    ]
].round(0)

salary_by_category

              category  job_offers  median_salary  q1_salary  q3_salary
28             Support          95        16800.0    12000.0    23050.0
31             Testing         297        19320.0    15960.0    23520.0
8               Design          42        19750.0    17057.0    23932.0
29  Sys. Administrator          32        20790.0    13944.0    24885.0
5    Business Analysis          61        21420.0    17585.0    25200.0
15            Frontend          75        23150.0    20750.0    26815.0
13            Embedded          44        23520.0    19375.0    25620.0
22              Mobile          56        23604.0    21357.0    26880.0
25     Project Manager         166        24045.0    20580.0    27665.0
26            Security         154        24335.0    20160.0    30555.0
16           Fullstack         296        24405.0    21315.0    28796.0
7                 Data         404        24588.0    21840.0    28560.0
4              Backend         624        24780.0    21000.0    29500.0
19             Inne IT          35        24990.0    20960.0    28938.0
24  Product Management          69        25200.0    21188.0    28140.0
0                   AI         178        25830.0    22044.0    30236.0
9               DevOps         282        26040.0    22545.0    30900.0
11                 ERP         102        28530.0    23955.0    31909.0
2         Architecture         122        30938.0    27555.0    33600.0

In [69]:
fig = px.bar(
    salary_by_category,
    x="median_salary",
    y="category",
    orientation="h",
    text="median_salary",
    title="Median Monthly Salary by Job Category",
    labels={
        "median_salary": "Median monthly salary (PLN)",
        "category": "Job category",
    },
)

fig.update_traces(
    texttemplate="%{text:,.0f} PLN",
    textposition="outside",
    cliponaxis=False,
)

fig.update_layout(
    showlegend=False,
    height=max(
        500,
        len(salary_by_category) * 38,
    ),
    xaxis_range=[
        0,
        salary_by_category["median_salary"].max() * 1.18,
    ],
)

fig.show()

In [70]:
senior_salary_by_category = (
    salary_df.loc[
        salary_df["experience"].eq("Senior")
    ]
    .dropna(subset=["category"])
    .groupby("category")
    .agg(
        job_offers=("job_id", "nunique"),
        median_salary=(
            "salary_mid_pln_monthly",
            "median",
        ),
    )
    .reset_index()
    .query("job_offers >= 20")
    .sort_values("median_salary")
)

senior_salary_by_category["median_salary"] = (
    senior_salary_by_category["median_salary"]
    .round(0)
)

senior_salary_by_category

              category  job_offers  median_salary
26             Testing         150        21753.0
8               Design          22        22170.0
5    Business Analysis          30        23100.0
13            Frontend          44        23835.0
23             Support          30        24135.0
11            Embedded          26        24680.0
20     Project Manager          96        24780.0
18              Mobile          34        24780.0
7                 Data         245        25500.0
19  Product Management          39        25536.0
21            Security          74        25635.0
14           Fullstack         176        26000.0
4              Backend         391        26040.0
0                   AI         112        26690.0
9               DevOps         178        26880.0
10                 ERP          68        29400.0
2         Architecture          72        30950.0

In [71]:
fig = px.bar(
    senior_salary_by_category,
    x="median_salary",
    y="category",
    orientation="h",
    text="median_salary",
    title="Median Monthly Salary for Senior Roles by Category",
    labels={
        "median_salary": "Median monthly salary (PLN)",
        "category": "Job category",
    },
)

fig.update_traces(
    texttemplate="%{text:,.0f} PLN",
    textposition="outside",
    cliponaxis=False,
)

fig.update_layout(
    showlegend=False,
    height=max(
        500,
        len(senior_salary_by_category) * 40,
    ),
    xaxis_range=[
        0,
        senior_salary_by_category["median_salary"].max() * 1.2,
    ],
)

fig.show()

In [72]:
show_summary('All levels: ' + salary_summary(salary_by_category, 'category'),
    'Senior only: ' + salary_summary(senior_salary_by_category, 'category'),
    "Minimum samples: 30 overall, 20 Senior offers. Restricting experience does not control all confounding factors.")

### Calculated summary

- All levels: Highest median among included groups: Architecture: PLN 30,938 (n=122). Differences are descriptive.
- Senior only: Highest median among included groups: Architecture: PLN 30,950 (n=72). Differences are descriptive.
- Minimum samples: 30 overall, 20 Senior offers. Restricting experience does not control all confounding factors.

### 7.4 Salary by contract type

Compare the three principal reported contract groups. Rare and missing contract types remain in the dataset but are excluded from this chart.

In [73]:
def simplify_contract_type(value):
    if pd.isna(value):
        return "Missing"

    contracts = {
        item.strip()
        for item in str(value).split(",")
    }

    if {
        "B2B",
        "Umowa o pracę",
    }.issubset(contracts):
        return "B2B + UoP"

    if "B2B" in contracts:
        return "B2B"

    if "Umowa o pracę" in contracts:
        return "UoP"

    return "Other"


salary_df["contract_group"] = (
    salary_df["contract_type"]
    .apply(simplify_contract_type)
)

In [74]:
main_contracts = [
    "UoP",
    "B2B + UoP",
    "B2B",
]

contract_salary_plot = salary_df.loc[
    salary_df["contract_group"].isin(main_contracts)
].copy()

In [75]:
salary_by_contract = (
    contract_salary_plot
    .groupby("contract_group")
    .agg(
        job_offers=("job_id", "nunique"),
        median_salary=("salary_mid_pln_monthly", "median"),
        q1_salary=("salary_mid_pln_monthly", lambda x: x.quantile(0.25)),
        q3_salary=("salary_mid_pln_monthly", lambda x: x.quantile(0.75)),
    )
    .round(0)
    .reset_index()
)

salary_by_contract

  contract_group  job_offers  median_salary  q1_salary  q3_salary
0            B2B        2423        24360.0    20685.0    28560.0
1      B2B + UoP         204        28350.0    25150.0    32550.0
2            UoP         119        20500.0    17000.0    31484.0

In [76]:
fig = px.box(
    contract_salary_plot,
    x="contract_group",
    y="salary_mid_pln_monthly",
    category_orders={
        "contract_group": main_contracts,
    },
    points=False,
    title="Monthly Salary Distribution by Contract Type",
    labels={
        "contract_group": "Contract type",
        "salary_mid_pln_monthly":
            "Monthly salary midpoint (PLN)",
    },
)

fig.update_layout(
    showlegend=False,
    height=520,
)

fig.show()

In [77]:
show_summary(salary_summary(salary_by_contract, 'contract_group'),
    "B2B and employment-contract amounts differ in taxes, benefits and paid leave; they are not take-home equivalents.")

### Calculated summary

- Highest median among included groups: B2B + UoP: PLN 28,350 (n=204). Differences are descriptive.
- B2B and employment-contract amounts differ in taxes, benefits and paid leave; they are not take-home equivalents.

### 7.5 Salary by workplace model

Compare workplace groups with at least 30 salary observations and repeat the analysis for Senior roles.

In [78]:
workplace_counts = (
    salary_df["workplace"]
    .value_counts()
)

valid_workplaces = workplace_counts[
    workplace_counts >= 30
].index

workplace_salary_df = salary_df.loc[
    salary_df["workplace"].isin(valid_workplaces)
].copy()

In [79]:
salary_by_workplace = (
    workplace_salary_df
    .groupby("workplace")
    .agg(
        job_offers=("job_id", "nunique"),
        median_salary=("salary_mid_pln_monthly", "median"),
        q1_salary=("salary_mid_pln_monthly", lambda x: x.quantile(0.25)),
        q3_salary=("salary_mid_pln_monthly", lambda x: x.quantile(0.75)),
    )
    .round(0)
    .reset_index()
    .sort_values("median_salary")
)

salary_by_workplace

  workplace  job_offers  median_salary  q1_salary  q3_salary
0    Hybrid        1700        24150.0    20000.0    29400.0
1    Remote         999        24780.0    21000.0    28560.0

In [80]:
workplace_order = [
    workplace
    for workplace in ["Onsite", "Hybrid", "Remote"]
    if workplace in valid_workplaces
]

fig = px.box(
    workplace_salary_df,
    x="workplace",
    y="salary_mid_pln_monthly",
    category_orders={
        "workplace": workplace_order,
    },
    points=False,
    title="Monthly Salary Distribution by Workplace Model",
    labels={
        "workplace": "Workplace model",
        "salary_mid_pln_monthly":
            "Monthly salary midpoint (PLN)",
    },
)

fig.update_layout(
    showlegend=False,
    height=520,
)

fig.show()

In [81]:
senior_workplace_salary = (
    salary_df.loc[
        salary_df["experience"].eq("Senior")
        & salary_df["workplace"].isin(
            ["Remote", "Hybrid", "Onsite"]
        )
    ]
    .copy()
)

In [82]:
senior_workplace_counts = (
    senior_workplace_salary["workplace"]
    .value_counts()
)

valid_senior_workplaces = (
    senior_workplace_counts[
        senior_workplace_counts >= 30
    ]
    .index
)

senior_workplace_salary = (
    senior_workplace_salary.loc[
        senior_workplace_salary["workplace"].isin(
            valid_senior_workplaces
        )
    ]
    .copy()
)

In [83]:
senior_salary_by_workplace = (
    senior_workplace_salary
    .groupby("workplace")
    .agg(
        job_offers=("job_id", "nunique"),
        median_salary=(
            "salary_mid_pln_monthly",
            "median",
        ),
        q1_salary=(
            "salary_mid_pln_monthly",
            lambda x: x.quantile(0.25),
        ),
        q3_salary=(
            "salary_mid_pln_monthly",
            lambda x: x.quantile(0.75),
        ),
    )
    .round(0)
    .reset_index()
    .sort_values("median_salary")
)

senior_salary_by_workplace

  workplace  job_offers  median_salary  q1_salary  q3_salary
1    Remote         675        25500.0    22680.0    29400.0
0    Hybrid         904        25520.0    22442.0    30240.0

In [84]:
fig = px.box(
    senior_workplace_salary,
    x="workplace",
    y="salary_mid_pln_monthly",
    points=False,
    title="Monthly Salary for Senior Roles by Workplace Model",
    labels={
        "workplace": "Workplace model",
        "salary_mid_pln_monthly":
            "Monthly salary midpoint (PLN)",
    },
)

fig.update_layout(
    showlegend=False,
    height=520,
)

fig.show()

In [85]:
show_summary('All levels: ' + salary_summary(salary_by_workplace, 'workplace'),
    'Senior only: ' + salary_summary(senior_salary_by_workplace, 'workplace'),
    "Each group includes at least 30 offers. Median differences alone do not establish a workplace salary premium.")

### Calculated summary

- All levels: Highest median among included groups: Remote: PLN 24,780 (n=999). Differences are descriptive.
- Senior only: Highest median among included groups: Hybrid: PLN 25,520 (n=904). Differences are descriptive.
- Each group includes at least 30 offers. Median differences alone do not establish a workplace salary premium.

### 7.6 Salary by company size

Compare salary distributions across known company-size segments. Offers with missing company size are excluded only from this comparison.

In [86]:
company_size_order = [
    "Small",
    "Medium",
    "Large",
    "Enterprise",
]

company_size_salary_df = salary_df.loc[
    salary_df["company_size_segment"].isin(
        company_size_order
    )
].copy()

In [87]:
salary_by_company_size = (
    company_size_salary_df
    .groupby(
        "company_size_segment",
        observed=True,
    )
    .agg(
        job_offers=("job_id", "nunique"),
        median_salary=(
            "salary_mid_pln_monthly",
            "median",
        ),
        q1_salary=(
            "salary_mid_pln_monthly",
            lambda x: x.quantile(0.25),
        ),
        q3_salary=(
            "salary_mid_pln_monthly",
            lambda x: x.quantile(0.75),
        ),
    )
    .round(0)
    .reset_index()
)

salary_by_company_size["company_size_segment"] = (
    pd.Categorical(
        salary_by_company_size[
            "company_size_segment"
        ],
        categories=company_size_order,
        ordered=True,
    )
)

salary_by_company_size = (
    salary_by_company_size
    .sort_values("company_size_segment")
)

salary_by_company_size

  company_size_segment  job_offers  median_salary  q1_salary  q3_salary
3                Small         184        25200.0    20120.0    28500.0
2               Medium         486        24780.0    20000.0    29400.0
1                Large        1095        24269.0    20500.0    28560.0
0           Enterprise         580        22680.0    18975.0    26880.0

In [88]:
fig = px.violin(
    company_size_salary_df,
    x="company_size_segment",
    y="salary_mid_pln_monthly",
    category_orders={
        "company_size_segment":
            company_size_order,
    },
    box=True,
    points=False,
    title="Monthly Salary Distribution by Company Size",
    labels={
        "company_size_segment": "Company size",
        "salary_mid_pln_monthly":
            "Monthly salary midpoint (PLN)",
    },
)

fig.update_layout(
    showlegend=False,
    height=550,
)

fig.show()

In [89]:
show_summary(salary_summary(salary_by_company_size, 'company_size_segment'),
    "Unknown sizes are excluded; experience, category and contract composition can explain differences.")

### Calculated summary

- Highest median among included groups: Small: PLN 25,200 (n=184). Differences are descriptive.
- Unknown sizes are excluded; experience, category and contract composition can explain differences.

### 7.7 Salary by experience and contract type

Compare contract groups within the same experience levels to reduce confounding from experience composition.

In [90]:
experience_contract_salary = (
    contract_salary_plot
    .dropna(subset=["experience"])
    .groupby(
        [
            "experience",
            "contract_group",
        ],
        observed=True,
    )
    .agg(
        job_offers=("job_id", "nunique"),
        median_salary=(
            "salary_mid_pln_monthly",
            "median",
        ),
    )
    .reset_index()
)



experience_contract_salary[
    "median_salary"
] = (
    experience_contract_salary[
        "median_salary"
    ]
    .round(0)
)

experience_contract_salary

   experience contract_group  job_offers  median_salary
0      Expert            B2B         100        30471.0
1      Expert      B2B + UoP           7        33600.0
2      Expert            UoP           5        24311.0
3      Junior            B2B          64        13860.0
4      Junior      B2B + UoP          12        18086.0
5      Junior            UoP           9        13225.0
6         Mid            B2B         810        21000.0
7         Mid      B2B + UoP          88        27300.0
8         Mid            UoP          38        17712.0
9      Senior            B2B        1430        25200.0
10     Senior      B2B + UoP          97        29400.0
11     Senior            UoP          61        23342.0

In [91]:
fig = px.bar(
    experience_contract_salary,
    x="experience",
    y="median_salary",
    color="contract_group",
    barmode="group",
    text="median_salary",
    category_orders={
        "experience": experience_order,
        "contract_group": [
            "UoP",
            "B2B + UoP",
            "B2B",
        ],
    },
    title="Median Monthly Salary by Experience and Contract Type",
    labels={
        "experience": "Experience level",
        "median_salary":
            "Median monthly salary (PLN)",
        "contract_group": "Contract type",
    },
)

fig.update_traces(
    texttemplate="%{text:,.0f}",
    textposition="outside",
    cliponaxis=False,
)

fig.update_layout(
    height=550,
    legend_title_text="Contract type",
)

fig.show()

In [92]:
show_summary(f"Observed experience-contract groups: {len(experience_contract_salary):,}.",
    "Review counts alongside medians; small groups are descriptive and contract amounts are not equivalent.")
display(experience_contract_salary)

### Calculated summary

- Observed experience-contract groups: 12.
- Review counts alongside medians; small groups are descriptive and contract amounts are not equivalent.

   experience contract_group  job_offers  median_salary
0      Expert            B2B         100        30471.0
1      Expert      B2B + UoP           7        33600.0
2      Expert            UoP           5        24311.0
3      Junior            B2B          64        13860.0
4      Junior      B2B + UoP          12        18086.0
5      Junior            UoP           9        13225.0
6         Mid            B2B         810        21000.0
7         Mid      B2B + UoP          88        27300.0
8         Mid            UoP          38        17712.0
9      Senior            B2B        1430        25200.0
10     Senior      B2B + UoP          97        29400.0
11     Senior            UoP          61        23342.0

### 7.8 Salary-information availability

Measure whether salary transparency differs between experience levels and identify possible representation bias in salary comparisons.

In [93]:
salary_availability = (
    df.dropna(subset=["experience"])
    .groupby(
        "experience",
        observed=True,
    )
    .agg(
        all_offers=("job_id", "nunique"),
        offers_with_salary=(
            "salary_normalization_eligible",
            "sum",
        ),
    )
    .reset_index()
)

salary_availability["salary_available_pct"] = (
    salary_availability["offers_with_salary"]
    / salary_availability["all_offers"]
    * 100
).round(1)

salary_availability["experience"] = pd.Categorical(
    salary_availability["experience"],
    categories=experience_order,
    ordered=True,
)

salary_availability = (
    salary_availability
    .sort_values("experience")
)

salary_availability

  experience  all_offers  offers_with_salary  salary_available_pct
1     Junior         199                 121                  60.8
2        Mid        1639                1089                  66.4
3     Senior        2451                1862                  76.0
0     Expert         204                 144                  70.6

In [94]:
fig = px.bar(
    salary_availability,
    x="experience",
    y="salary_available_pct",
    text="salary_available_pct",
    category_orders={
        "experience": experience_order,
    },
    title="Salary Information Availability by Experience Level",
    labels={
        "experience": "Experience level",
        "salary_available_pct":
            "Offers with salary information (%)",
    },
)

fig.update_traces(
    texttemplate="%{text:.1f}%",
    textposition="outside",
    cliponaxis=False,
)

fig.update_layout(
    showlegend=False,
    height=500,
    yaxis_range=[0, 100],
)

fig.show()

In [95]:
show_summary("Salary availability means a complete range with a recognized currency and period, before the quality filter.",
    "Denominators include all offers in each known experience level. Missing experience is excluded.")
display(salary_availability)

### Calculated summary

- Salary availability means a complete range with a recognized currency and period, before the quality filter.
- Denominators include all offers in each known experience level. Missing experience is excluded.

  experience  all_offers  offers_with_salary  salary_available_pct
1     Junior         199                 121                  60.8
2        Mid        1639                1089                  66.4
3     Senior        2451                1862                  76.0
0     Expert         204                 144                  70.6

## 8. Location Analysis

This section examines the geographical distribution of job offers,
workplace models and salary differences across the most frequently
reported locations.

### 8.1 Geographical distribution

In [96]:
assert not df["job_locations"].eq("Warsaw, Poland").any()
assert df["job_locations"].notna().all()

In [97]:
only_cities = df.loc[
    ~df["job_locations"].isin(
        ["Remote", "Missing"]
    )
].copy()

In [98]:
city_ranking = only_cities.groupby('job_locations')['job_id'].nunique()

In [99]:
top_10_cities = (
    city_ranking
    .sort_values(ascending=False)
    .head(10)
    .rename("job_offers")
    .reset_index()
    .sort_values("job_offers")
)

fig = px.bar(
    top_10_cities,
    x="job_offers",
    y="job_locations",
    orientation="h",
    text="job_offers",
    title="Cities with the Highest Number of Job Offers",
    labels={
        "job_offers": "Number of job offers",
        "job_locations": "City",
    },
)

fig.update_traces(
    textposition="outside",
    cliponaxis=False,
)

fig.update_layout(
    showlegend=False,
    yaxis_title=None,
    xaxis_range=[
        0,
        top_10_cities["job_offers"].max() * 1.12,
    ],
)

fig.show()

### 8.2 Experience level by city

In [100]:
top_8_cities = (
    city_ranking
    .sort_values(ascending=False)
    .head(8)
    .index
)

city_experience_df = (
    only_cities.loc[
        only_cities["job_locations"].isin(
            top_8_cities
        )
    ]
    .dropna(subset=["experience"])
)

In [101]:
city_experience = (
    pd.crosstab(
        city_experience_df["job_locations"],
        city_experience_df["experience"],
        normalize="index",
    )
    .mul(100)
    .round(1)
)

In [102]:
experience_order = [
    "Junior",
    "Mid",
    "Senior",
    "Expert",
]

city_experience = city_experience.reindex(
    index=top_8_cities,
    columns=experience_order,
    fill_value=0,
)

city_experience

experience     Junior   Mid  Senior  Expert
job_locations
Warszawa          4.4  42.9    49.7     3.0
Kraków            3.6  39.3    51.0     6.1
Wrocław          12.2  41.0    41.9     5.0
Katowice         15.3  44.7    35.3     4.7
Gdańsk            1.5  27.5    64.1     6.9
Poznań           13.4  25.6    57.3     3.7
Łódź              7.7  32.3    55.4     4.6
Gdynia            0.0  43.6    48.7     7.7

In [103]:
fig = px.imshow(
    city_experience,
    text_auto=".1f",
    aspect="auto",
    color_continuous_scale="Blues",
    title="Experience Level Distribution by City",
    labels={
        "x": "Experience level",
        "y": "City",
        "color": "Share of job offers (%)",
    },
)

fig.update_layout(
    height=550,
)

fig.show()

### 8.3 Salary by city

In [104]:
salary_location_df = (
    salary_df
    .drop(
        columns=["job_locations"],
        errors="ignore",
    )
    .merge(
        df[
            [
                "job_id",
                "job_locations",
            ]
        ],
        on="job_id",
        how="left",
        validate="one_to_one",
    )
)

salary_location_df = salary_location_df.loc[
    ~salary_location_df["job_locations"].isin(
        ["Remote", "Missing"]
    )
].copy()

In [105]:
salary_by_city = (
    salary_location_df
    .groupby("job_locations")
    .agg(
        job_offers=("job_id", "nunique"),
        median_salary=(
            "salary_mid_pln_monthly",
            "median",
        ),
        q1_salary=(
            "salary_mid_pln_monthly",
            lambda x: x.quantile(0.25),
        ),
        q3_salary=(
            "salary_mid_pln_monthly",
            lambda x: x.quantile(0.75),
        ),
    )
    .reset_index()
    .query("job_offers >= 30")
)

salary_by_city[
    [
        "median_salary",
        "q1_salary",
        "q3_salary",
    ]
] = (
    salary_by_city[
        [
            "median_salary",
            "q1_salary",
            "q3_salary",
        ]
    ]
    .round(0)
)

salary_by_city = salary_by_city.sort_values(
    "median_salary"
)

salary_by_city

   job_locations  job_offers  median_salary  q1_salary  q3_salary
7         Poznań          70        18125.0    13225.0    23177.0
4       Katowice          73        18750.0    14000.0    22500.0
13       Wrocław         136        19462.0    15000.0    23286.0
1         Gdańsk          76        22890.0    19870.0    27790.0
12      Warszawa         794        24000.0    20040.0    29308.0
5         Kraków         624        26250.0    22050.0    30450.0

In [106]:
fig = px.bar(
    salary_by_city,
    x="median_salary",
    y="job_locations",
    orientation="h",
    text="median_salary",
    title="Median Monthly Salary by City",
    labels={
        "median_salary":
            "Median monthly salary (PLN)",
        "job_locations": "City",
    },
    hover_data={
        "job_offers": True,
        "q1_salary": ":,.0f",
        "q3_salary": ":,.0f",
        "median_salary": ":,.0f",
    },
)

fig.update_traces(
    texttemplate="%{text:,.0f} PLN",
    textposition="outside",
    cliponaxis=False,
)

fig.update_layout(
    showlegend=False,
    yaxis_title=None,
    xaxis_range=[
        0,
        salary_by_city[
            "median_salary"
        ].max() * 1.18,
    ],
)

fig.show()

In [107]:
senior_salary_by_city = (
    salary_location_df.loc[
        salary_location_df["experience"].eq(
            "Senior"
        )
    ]
    .groupby("job_locations")
    .agg(
        senior_offers=("job_id", "nunique"),
        senior_median_salary=(
            "salary_mid_pln_monthly",
            "median",
        ),
        senior_q1_salary=(
            "salary_mid_pln_monthly",
            lambda x: x.quantile(0.25),
        ),
        senior_q3_salary=(
            "salary_mid_pln_monthly",
            lambda x: x.quantile(0.75),
        ),
    )
    .reset_index()
    .query("senior_offers >= 20")
)

senior_salary_by_city[
    [
        "senior_median_salary",
        "senior_q1_salary",
        "senior_q3_salary",
    ]
] = (
    senior_salary_by_city[
        [
            "senior_median_salary",
            "senior_q1_salary",
            "senior_q3_salary",
        ]
    ]
    .round(0)
)

senior_salary_by_city = (
    senior_salary_by_city
    .sort_values("senior_median_salary")
)

senior_salary_by_city

,job_locations,senior_offers,senior_median_salary,senior_q1_salary,senior_q3_salary
3,Katowice,27,20160.0,18500.0,25200.0
5,Poznań,36,20500.0,16076.0,23622.0
8,Wrocław,55,22050.0,20500.0,25000.0
9,Łódź,20,22260.0,19746.0,24835.0
1,Gdańsk,50,24990.0,21932.0,33764.0
7,Warszawa,418,25620.0,22680.0,31060.0
4,Kraków,324,26880.0,23400.0,30240.0

In [108]:
city_salary_comparison = (
    salary_by_city[
        [
            "job_locations",
            "job_offers",
            "median_salary",
        ]
    ]
    .merge(
        senior_salary_by_city[
            [
                "job_locations",
                "senior_offers",
                "senior_median_salary",
            ]
        ],
        on="job_locations",
        how="inner",
    )
)

city_salary_comparison

,job_locations,job_offers,median_salary,senior_offers,senior_median_salary
0,Poznań,70,18125.0,36,20500.0
1,Katowice,73,18750.0,27,20160.0
2,Wrocław,136,19462.0,55,22050.0
3,Gdańsk,76,22890.0,50,24990.0
4,Warszawa,794,24000.0,418,25620.0
5,Kraków,624,26250.0,324,26880.0

In [109]:
city_salary_plot = (
    city_salary_comparison
    .melt(
        id_vars=[
            "job_locations",
            "job_offers",
            "senior_offers",
        ],
        value_vars=[
            "median_salary",
            "senior_median_salary",
        ],
        var_name="salary_group",
        value_name="median_salary_pln",
    )
)

city_salary_plot["salary_group"] = (
    city_salary_plot["salary_group"]
    .replace({
        "median_salary": "All experience levels",
        "senior_median_salary": "Senior only",
    })
)

In [110]:
fig = px.bar(
    city_salary_plot,
    x="job_locations",
    y="median_salary_pln",
    color="salary_group",
    barmode="group",
    text="median_salary_pln",
    title="Median Monthly Salary by City: All Roles vs Senior Roles",
    labels={
        "job_locations": "City",
        "median_salary_pln":
            "Median monthly salary (PLN)",
        "salary_group": "Salary group",
    },
    hover_data={
        "job_offers": True,
        "senior_offers": True,
        "median_salary_pln": ":,.0f",
    },
)

fig.update_traces(
    texttemplate="%{text:,.0f}",
    textposition="outside",
    cliponaxis=False,
)

fig.update_layout(
    height=550,
    legend_title_text=None,
)

fig.show()

In [111]:
show_summary(f"Offers assigned a non-Remote, non-Missing location: {len(only_cities):,} ({len(only_cities)/len(df):.1%}).",
    salary_summary(salary_by_city, 'job_locations'),
    "Prepared location labels may simplify multi-location offers; counts do not describe regional market size.")

### Calculated summary

- Offers assigned a non-Remote, non-Missing location: 2,824 (61.7%).
- Highest median among included groups: Kraków: PLN 26,250 (n=624). Differences are descriptive.
- Prepared location labels may simplify multi-location offers; counts do not describe regional market size.

## 9. Skills Analysis

This section examines the availability and structure of required and
optional skill information before identifying the most frequently
requested technologies.

### 9.1 Skills data quality

In [112]:
skills_quality = pd.DataFrame({
    "column": [
        "required_skills",
        "nice_to_have",
    ],
    "available": [
        df["required_skills"].notna().sum(),
        df["nice_to_have"].notna().sum(),
    ],
    "missing": [
        df["required_skills"].isna().sum(),
        df["nice_to_have"].isna().sum(),
    ],
    "unique_values": [
        df["required_skills"].nunique(),
        df["nice_to_have"].nunique(),
    ],
})

skills_quality["available_pct"] = (
    skills_quality["available"]
    / len(df)
    * 100
).round(1)

skills_quality

            column  available  missing  unique_values  available_pct
0  required_skills       4569        8           4259           99.8
1     nice_to_have       2761     1816           2233           60.3

In [113]:
skills_sample = (
    df.loc[
        df["required_skills"].notna(),
        [
            "title",
            "category",
            "required_skills",
            "nice_to_have",
        ],
    ]
    .drop_duplicates(
        subset=["required_skills"]
    )
    .sample(
        n=min(
            30,
            df["required_skills"]
            .nunique(),
        ),
        random_state=42,
    )
)

skills_sample

,title,category,required_skills,nice_to_have
185,AVP - Financial Accounting Operations HBUK,Backend,IFRS FTP Excel Audit Saracen,Accounting Python Appian Qlik Sense Regulated ...
1047,IT Product Owner,Project Manager,User stories Jira Confluence PSPO II R API Ang...,UX SQL AI
3481,Cloud Security Engineer Azure,Security,Azure Security microsoft 365 Python Powershell...,None
2854,Software Engineer Internship Kraków,Telekomunikacja,Git Python C Angielski,C++
612,DevOps Engineer with German language,DevOps,CI/CD Cloud Linux Docker Bash Git Angielski (B...,Kubernetes AI Ansible Puppet
2700,Senior Systems Engineer - Orchestration Services,DevOps,Linux Ubuntu Storage Kubernetes Docker Git Bas...,GitLab GitHub Vault BGP Cloud GCP Python Golang
1274,Linux Platform Engineer,DevOps,Linux Operating system KVM Virtualisation Netw...,Git Jenkins
447,Data Collection SW Engineer / Graduate,Data,C++ Java Phyton Linux Jira Rust Angielski (B2),None
2458,Senior NetApp Storage Engineer,Support,NetApp Storage Active Directory NetBackup Angi...,None
109,Analytics Engineer,Data,SQL GCP Oracle Python Angielski (C1) Polski (B2),None
221,"Backend Engineer (Java, SpringBoot, Microservi...",Backend,Java Spring Boot Microservices Degree Git Gitf...,Kotlin Node.js Cloud platform AWS Azure Micros...
1190,Kierownik IT (K/M),Inne IT,Dyrektor IT Head of IT CIO Team management Mic...,None
3905,.Net Developer,Backend,.NET Entity Framework PostgreSQL REST API AWS ...,Go Open API Angielski (C1)
1408,Multimedia Engineer,Embedded,Linux AOSP Android Git Angielski (B2),ISP OpenCV
4077,SAP CPI Consultant,ERP,REST API SOAP OData Angielski (B2),ABAP
3354,Test Automation Engineer,Testing,Java Selenium Playwright Cucumber Git GitLab J...,None
4459,Specjalista ds. Social Media i Grafiki (m/k),Marketing,Social media Graphic design Angielski (B2),None
4066,SAP Analytics Cloud & Datasphere Planning Expert,ERP,SAP Analytics Cloud SAP SQL JavaScript SAP BW ...,Agile Jira Project management
1340,Microsoft Dynamics CRM Consultant,ERP,Microsoft Dynamics CRM Analiza problemów Diagn...,Branża telekomunikacyjna
3744,It Infrastructure Specialist,Architecture,WebLogic Kubernetes Security ITIL BMC SLA Graf...,CI/CD Maven Bitbucket Kafka Agile SAFe Jira
2434,Senior .NET Developer,Backend,.NET C# DDD CQRS OpenAPI BDD REST API OOP Clea...,None
1492,Pentester WebAPP and API,Security,Security Cybersecurity Web applications Active...,OSWE Cloud AWS Azure GCP Kubernetes
1149,Junior Front-end Developer [VUE],Frontend,HTML CSS JavaScript Bootstrap Tailwind Vue.js ...,PHP CMS WordPress MySQL MariaDB PostgreSQL
2349,Senior Java Developer – Risk Technology,Backend,Java Multithreading Java REST API RDBMS SQL JV...,PostgreSQL Apache Kafka Oracle PL/SQL Linux Sh...
1106,Java Developer,Backend,Java Spring Framework Hibernate Microservices ...,None
4086,SAP FI Consultant,ERP,SAP Accounting Requirements gathering User sto...,Degree Cloud ABAP
1276,Linux Systems Specialist - German Speaking,Backend,Linux Virtualisation SAN Storage Angielski Nie...,None
1421,.NET Developer + Kafka,Backend,C# .NET .NET Core SQL Kafka Angielski Polski,AI
3828,Lead & Business Partner,Project Manager,Transmission Control Protocol Migration Angielski,Microsoft
2193,Senior Experience Designer,Design,UX design AI Figma Angielski,None

In [114]:
df["required_skills_length"] = (
    df["required_skills"]
    .fillna("")
    .str.len()
)

df["required_skills_length"].describe()

count    4577.000000
mean       78.917195
std        51.889090
min         0.000000
25%        42.000000
50%        68.000000
75%       101.000000
max       435.000000
Name: required_skills_length, dtype: float64

### 9.2 Most frequently required technologies

In [115]:
skill_candidates = [
    "Python",
    "SQL",
    "Java",
    "JavaScript",
    "TypeScript",
    "C#",
    "C++",
    ".NET",
    "React",
    "Angular",
    "Vue.js",
    "Node.js",
    "Spring",
    "Spring Boot",
    "pandas",
    "NumPy",
    "scikit-learn",
    "TensorFlow",
    "PyTorch",
    "Power BI",
    "Tableau",
    "Excel",
    "AWS",
    "Azure",
    "GCP",
    "Docker",
    "Kubernetes",
    "Terraform",
    "Git",
    "Jenkins",
    "Linux",
    "Spark",
    "Kafka",
    "Snowflake",
    "PostgreSQL",
    "MongoDB",
    "Oracle",
    "REST API",
    "Machine Learning",
]

In [116]:
skills_text = (
    df["required_skills"]
    .fillna("")
)

skill_frequency = []

for skill in skill_candidates:
    pattern = (
        rf"(?<!\w)"
        rf"{re.escape(skill)}"
        rf"(?!\w)"
    )

    job_offers = (
        skills_text
        .str.contains(
            pattern,
            case=False,
            regex=True,
        )
        .sum()
    )

    skill_frequency.append({
        "skill": skill,
        "job_offers": job_offers,
    })

skill_frequency = (
    pd.DataFrame(skill_frequency)
    .sort_values(
        "job_offers",
        ascending=False,
    )
    .reset_index(drop=True)
)

skill_frequency.head(20)

         skill  job_offers
0       Python        1017
1          SQL         972
2         Java         755
3        Azure         608
4     REST API         549
5          Git         480
6          AWS         464
7   Kubernetes         451
8       Docker         375
9        Linux         340
10  TypeScript         322
11      Spring         306
12        .NET         300
13  JavaScript         300
14       React         291
15         GCP         251
16  PostgreSQL         241
17   Terraform         232
18          C#         232
19     Jenkins         230

In [117]:
top_15_skills = (
    skill_frequency
    .query("job_offers > 0")
    .head(15)
    .copy()
)

top_15_skills["offer_share_pct"] = (
    top_15_skills["job_offers"]
    / df["required_skills"].notna().sum()
    * 100
).round(1)

top_15_skills = (
    top_15_skills
    .sort_values("job_offers")
)

top_15_skills

         skill  job_offers  offer_share_pct
14       React         291              6.4
12        .NET         300              6.6
13  JavaScript         300              6.6
11      Spring         306              6.7
10  TypeScript         322              7.0
9        Linux         340              7.4
8       Docker         375              8.2
7   Kubernetes         451              9.9
6          AWS         464             10.2
5          Git         480             10.5
4     REST API         549             12.0
3        Azure         608             13.3
2         Java         755             16.5
1          SQL         972             21.3
0       Python        1017             22.3

In [118]:
fig = px.bar(
    top_15_skills,
    x="job_offers",
    y="skill",
    orientation="h",
    text="job_offers",
    title="Most Frequently Required Technologies",
    labels={
        "job_offers": "Number of job offers",
        "skill": "Technology",
    },
    hover_data={
        "offer_share_pct": ":.1f",
    },
)

fig.update_traces(
    textposition="outside",
    cliponaxis=False,
)

fig.update_layout(
    showlegend=False,
    height=650,
    margin=dict(
        l=100,
        r=70,
        t=70,
        b=50,
    ),
    yaxis=dict(
        title=None,
        tickmode="array",
        tickvals=top_15_skills["skill"],
        ticktext=top_15_skills["skill"],
        automargin=True,
    ),
    xaxis_range=[
        0,
        top_15_skills["job_offers"].max() * 1.15,
    ],
)

fig.show()

In [119]:
skill_rows = []

for skill in skill_candidates:
    pattern = (
        rf"(?<!\w)"
        rf"{re.escape(skill)}"
        rf"(?!\w)"
    )

    skill_mask = (
        df["required_skills"]
        .fillna("")
        .str.contains(
            pattern,
            case=False,
            regex=True,
        )
    )

    skill_rows.append(
        df.loc[
            skill_mask,
            [
                "job_id",
                "experience",
                "category",
                "salary_mid_pln_monthly",
                "salary_analysis_eligible",
            ],
        ]
        .assign(skill=skill)
    )

skills_long = (
    pd.concat(
        skill_rows,
        ignore_index=True,
    )
    .drop_duplicates(
        subset=[
            "job_id",
            "skill",
        ]
    )
)

skills_long.head()

,job_id,experience,category,salary_mid_pln_monthly,salary_analysis_eligible,skill
0,administrator-systemow-it-upvanta-wroclaw,Mid,Sys. Administrator,12075.0,True,Python
1,administrator-systemow-kubernetes-linux-aws-up...,Mid,Sys. Administrator,12075.0,True,Python
2,administrator-systemow-linux-unity-t-group-kra...,Mid,Sys. Administrator,12500.0,True,Python
3,agentic-ai-technical-consultant-poland-deloitt...,Mid,AI,NaN,False,Python
4,agentic-ai-technical-senior-consultant-poland-...,Senior,AI,NaN,False,Python

In [120]:
print("Unique offers:", skills_long["job_id"].nunique())
print("Offer-skill pairs:", len(skills_long))
print("Recognized technologies:", skills_long["skill"].nunique())

Unique offers: 3226
Offer-skill pairs: 10465
Recognized technologies: 39

### 9.3 Technologies by experience and category

In [121]:
top_10_skill_names = (
    skill_frequency
    .query("job_offers > 0")
    .head(10)["skill"]
    .tolist()
)

In [122]:
skill_experience_counts = (
    skills_long.loc[
        skills_long["skill"].isin(
            top_10_skill_names
        )
    ]
    .dropna(subset=["experience"])
    .groupby(
        [
            "skill",
            "experience",
        ]
    )["job_id"]
    .nunique()
    .unstack(fill_value=0)
)

In [123]:
experience_offer_counts = (
    df.loc[
        df["required_skills"].notna()
        & df["experience"].notna()
    ]
    .groupby("experience")["job_id"]
    .nunique()
)

In [124]:
skill_experience_pct = (
    skill_experience_counts
    .div(
        experience_offer_counts,
        axis="columns",
    )
    .mul(100)
    .round(1)
)

skill_experience_pct = skill_experience_pct.reindex(
    index=top_10_skill_names,
    columns=[
        "Junior",
        "Mid",
        "Senior",
        "Expert",
    ],
    fill_value=0,
)

skill_experience_pct

experience  Junior   Mid  Senior  Expert
skill
Python        15.1  20.0    24.3    24.5
SQL           16.1  22.1    21.5    19.6
Java          16.6  14.6    18.1    12.3
Azure          5.0  11.0    15.3    16.7
REST API       5.0  11.6    13.1     7.4
Git            9.5  10.6    11.2     3.4
AWS            4.0   7.0    12.9    11.8
Kubernetes     6.0   7.6    11.6    13.2
Docker         7.5   7.1     9.2     6.4
Linux          8.0   7.7     7.4     5.9

In [125]:
fig = px.imshow(
    skill_experience_pct,
    text_auto=".1f",
    aspect="auto",
    color_continuous_scale="Blues",
    title="Technology Demand by Experience Level",
    labels={
        "x": "Experience level",
        "y": "Technology",
        "color": "Share of job offers (%)",
    },
)

fig.update_traces(
    texttemplate="%{z:.1f}%"
)

fig.update_layout(
    height=600,
    yaxis_title=None,
)

fig.show()

In [126]:
top_8_categories = (
    df["category"]
    .value_counts()
    .head(8)
    .index
)

In [127]:
skill_category_counts = (
    skills_long.loc[
        skills_long["skill"].isin(
            top_10_skill_names
        )
        & skills_long["category"].isin(
            top_8_categories
        )
    ]
    .groupby(
        [
            "skill",
            "category",
        ]
    )["job_id"]
    .nunique()
    .unstack(fill_value=0)
)

In [128]:
category_offer_counts = (
    df.loc[
        df["required_skills"].notna()
        & df["category"].isin(
            top_8_categories
        )
    ]
    .groupby("category")["job_id"]
    .nunique()
)

In [129]:
skill_category_pct = (
    skill_category_counts
    .div(
        category_offer_counts,
        axis="columns",
    )
    .mul(100)
    .round(1)
)

skill_category_pct = skill_category_pct.reindex(
    index=top_10_skill_names,
    columns=top_8_categories,
    fill_value=0,
)

skill_category_pct

category,Backend,Data,Testing,Fullstack,DevOps,AI,ERP,Project Manager
skill,,,,,,,,
Python,21.0,47.1,19.8,21.4,39.8,65.1,0.0,0.8
SQL,28.5,56.3,26.1,35.6,6.5,15.5,6.6,0.8
Java,43.7,6.9,23.6,36.6,10.3,6.0,1.7,1.2
Azure,11.3,17.9,10.2,16.8,29.5,25.8,4.5,5.0
REST API,24.8,5.6,17.3,27.5,3.0,7.9,9.1,1.2
Git,16.8,7.3,16.2,22.5,15.4,9.9,2.1,0.0
AWS,12.8,11.0,2.5,13.4,32.2,17.9,0.0,1.2
Kubernetes,15.5,3.5,1.0,13.4,44.7,11.5,0.4,0.8
Docker,15.8,5.0,3.3,19.0,20.3,10.7,0.4,0.8
Linux,8.0,2.9,4.6,2.9,29.5,5.2,0.8,0.8

In [130]:
fig = px.imshow(
    skill_category_pct,
    text_auto=".1f",
    aspect="auto",
    color_continuous_scale="Teal",
    title="Technology Demand by Job Category",
    labels={
        "x": "Job category",
        "y": "Technology",
        "color": "Share of job offers (%)",
    },
)

fig.update_traces(
    texttemplate="%{z:.1f}%"
)

fig.update_layout(
    height=620,
    yaxis_title=None,
)

fig.show()

### 9.4 Salary by technology

In [131]:
skill_salary_df = skills_long.loc[
    skills_long["salary_analysis_eligible"]
].copy()

In [132]:
salary_by_skill = (
    skill_salary_df
    .groupby("skill")
    .agg(
        job_offers=("job_id", "nunique"),
        median_salary=(
            "salary_mid_pln_monthly",
            "median",
        ),
        q1_salary=(
            "salary_mid_pln_monthly",
            lambda x: x.quantile(0.25),
        ),
        q3_salary=(
            "salary_mid_pln_monthly",
            lambda x: x.quantile(0.75),
        ),
    )
    .reset_index()
    .query("job_offers >= 30")
)

salary_by_skill[
    [
        "median_salary",
        "q1_salary",
        "q3_salary",
    ]
] = (
    salary_by_skill[
        [
            "median_salary",
            "q1_salary",
            "q3_salary",
        ]
    ]
    .round(0)
)

salary_by_skill = salary_by_skill.sort_values(
    "median_salary"
)

salary_by_skill

               skill  job_offers  median_salary  q1_salary  q3_salary
7              Excel          70        21630.0    17850.0    24596.0
4                 C#         174        23058.0    20104.0    27818.0
9                Git         374        23100.0    19500.0    26490.0
0               .NET         240        23520.0    20158.0    28035.0
11        JavaScript         224        23520.0    20160.0    27746.0
2            Angular         126        23520.0    21000.0    26490.0
27               SQL         733        23520.0    19740.0    27300.0
25          REST API         445        23625.0    21000.0    27720.0
12           Jenkins         185        23940.0    20100.0    29000.0
22          Power BI          49        23940.0    19320.0    28560.0
5                C++          79        23940.0    19000.0    26440.0
15             Linux         239        23940.0    19000.0    28035.0
35        TypeScript         250        23940.0    21000.0    27300.0
20            Oracle         107        24150.0    21000.0    27510.0
31       Spring Boot         175        24780.0    21840.0    28718.0
23           PyTorch          32        24890.0    21840.0    29008.0
30            Spring         248        25000.0    22000.0    29400.0
6             Docker         291        25000.0    22000.0    28560.0
21        PostgreSQL         197        25000.0    21000.0    29400.0
18           Node.js          89        25000.0    21000.0    27825.0
10              Java         582        25000.0    21500.0    29400.0
13             Kafka         187        25200.0    22680.0    30112.0
17           MongoDB          48        25200.0    21000.0    31725.0
26             React         216        25200.0    21840.0    29425.0
24            Python         758        25200.0    21840.0    29400.0
3              Azure         452        25568.0    21993.0    29400.0
1                AWS         347        25620.0    21985.0    30240.0
16  Machine Learning          75        26040.0    21840.0    30120.0
14        Kubernetes         358        26670.0    22685.0    31080.0
8                GCP         166        26880.0    23025.0    31054.0
29             Spark          68        26880.0    23075.0    30292.0
34         Terraform         180        27300.0    22770.0    31500.0
28         Snowflake          64        27720.0    22266.0    30240.0

In [133]:
fig = px.bar(
    salary_by_skill,
    x="median_salary",
    y="skill",
    orientation="h",
    text="median_salary",
    title="Median Monthly Salary by Required Technology",
    labels={
        "median_salary":
            "Median monthly salary (PLN)",
        "skill": "Technology",
    },
    hover_data={
        "job_offers": True,
        "q1_salary": ":,.0f",
        "q3_salary": ":,.0f",
    },
)

fig.update_traces(
    texttemplate="%{text:,.0f} PLN",
    textposition="outside",
    cliponaxis=False,
)

fig.update_layout(
    showlegend=False,
    height=max(
        550,
        len(salary_by_skill) * 36,
    ),
    yaxis_title=None,
    xaxis_range=[
        0,
        salary_by_skill[
            "median_salary"
        ].max() * 1.18,
    ],
)

fig.show()

In [134]:
senior_salary_by_skill = (
    skill_salary_df.loc[
        skill_salary_df["experience"].eq(
            "Senior"
        )
    ]
    .groupby("skill")
    .agg(
        senior_offers=("job_id", "nunique"),
        senior_median_salary=(
            "salary_mid_pln_monthly",
            "median",
        ),
    )
    .reset_index()
    .query("senior_offers >= 20")
)

senior_salary_by_skill[
    "senior_median_salary"
] = (
    senior_salary_by_skill[
        "senior_median_salary"
    ]
    .round(0)
)

In [135]:
skill_salary_comparison = (
    salary_by_skill[
        [
            "skill",
            "job_offers",
            "median_salary",
        ]
    ]
    .merge(
        senior_salary_by_skill,
        on="skill",
        how="inner",
    )
    .sort_values(
        "senior_median_salary"
    )
)

skill_salary_comparison

,skill,job_offers,median_salary,senior_offers,senior_median_salary
0,Excel,70,21630.0,34,22380.0
5,Angular,126,23520.0,82,24045.0
2,Git,374,23100.0,221,24360.0
1,C#,174,23058.0,106,24360.0
7,REST API,445,23625.0,271,24360.0
12,TypeScript,250,23940.0,154,24360.0
4,JavaScript,224,23520.0,131,24559.0
3,.NET,240,23520.0,147,24780.0
6,SQL,733,23520.0,419,24780.0
18,Node.js,89,25000.0,53,24780.0
13,Oracle,107,24150.0,60,25200.0
11,Linux,239,23940.0,132,25200.0
17,PostgreSQL,197,25000.0,131,25200.0
10,C++,79,23940.0,45,25200.0
14,Spring Boot,175,24780.0,114,25350.0
8,Jenkins,185,23940.0,108,25410.0
22,React,216,25200.0,134,26040.0
15,Spring,248,25000.0,159,26040.0
16,Docker,291,25000.0,182,26040.0
23,Python,758,25200.0,469,26040.0
24,Azure,452,25568.0,286,26040.0
9,Power BI,49,23940.0,25,26250.0
19,Java,582,25000.0,348,26355.0
25,AWS,347,25620.0,239,26460.0
21,MongoDB,48,25200.0,30,26466.0
26,Machine Learning,75,26040.0,42,26670.0
20,Kafka,187,25200.0,116,26880.0
27,Kubernetes,358,26670.0,231,26880.0
28,GCP,166,26880.0,104,26880.0
29,Spark,68,26880.0,41,26880.0
30,Terraform,180,27300.0,111,27300.0
31,Snowflake,64,27720.0,43,29000.0

In [136]:
skill_salary_plot = (
    skill_salary_comparison
    .melt(
        id_vars=[
            "skill",
            "job_offers",
            "senior_offers",
        ],
        value_vars=[
            "median_salary",
            "senior_median_salary",
        ],
        var_name="salary_group",
        value_name="median_salary_pln",
    )
)

skill_salary_plot["salary_group"] = (
    skill_salary_plot["salary_group"]
    .replace({
        "median_salary":
            "All experience levels",
        "senior_median_salary":
            "Senior only",
    })
)

In [137]:
fig = px.bar(
    skill_salary_plot,
    x="median_salary_pln",
    y="skill",
    color="salary_group",
    orientation="h",
    barmode="group",
    text="median_salary_pln",
    title=(
        "Median Monthly Salary by Technology: "
        "All Roles vs Senior Roles"
    ),
    labels={
        "median_salary_pln":
            "Median monthly salary (PLN)",
        "skill": "Technology",
        "salary_group": "Salary group",
    },
    hover_data={
        "job_offers": True,
        "senior_offers": True,
    },
)

fig.update_traces(
    texttemplate="%{text:,.0f}",
    textposition="outside",
    cliponaxis=False,
)

fig.update_layout(
    height=max(
        600,
        len(
            skill_salary_comparison
        ) * 45,
    ),
    yaxis_title=None,
    legend_title_text=None,
)

fig.show()

### 9.5 Technology combinations

In [138]:
from itertools import combinations
from collections import Counter

In [139]:
skills_per_offer = (
    skills_long
    .groupby("job_id")["skill"]
    .apply(
        lambda skills:
            sorted(set(skills))
    )
)

In [140]:
skill_pair_counter = Counter()

for skills in skills_per_offer:
    skill_pair_counter.update(
        combinations(skills, 2)
    )

In [141]:
skill_pairs = pd.DataFrame(
    [
        {
            "skill_1": pair[0],
            "skill_2": pair[1],
            "job_offers": count,
        }
        for pair, count
        in skill_pair_counter.items()
    ],
    columns=["skill_1", "skill_2", "job_offers"],
)

spring_boot_pair = (
    skill_pairs[
        [
            "skill_1",
            "skill_2",
        ]
    ]
    .apply(
        lambda row: set(row) == {
            "Spring",
            "Spring Boot",
        },
        axis=1,
    )
)

skill_pairs = (
    skill_pairs.loc[
        ~spring_boot_pair
    ]
    .sort_values(
        "job_offers",
        ascending=False,
    )
    .reset_index(drop=True)
)

skill_pairs["skill_pair"] = (
    skill_pairs["skill_1"]
    + " + "
    + skill_pairs["skill_2"]
)

skill_pairs.head(20)

       skill_1      skill_2  job_offers           skill_pair
0       Python          SQL         318         Python + SQL
1         Java       Spring         295        Java + Spring
2       Docker   Kubernetes         219  Docker + Kubernetes
3         Java          SQL         217           Java + SQL
4         Java  Spring Boot         208   Java + Spring Boot
5     REST API          SQL         206       REST API + SQL
6         Java     REST API         202      Java + REST API
7        Azure       Python         200       Azure + Python
8          AWS       Python         190         AWS + Python
9         .NET           C#         177            .NET + C#
10         Git          SQL         174            Git + SQL
11       Azure          SQL         166          Azure + SQL
12        .NET          SQL         166           .NET + SQL
13         Git     REST API         162       Git + REST API
14  Kubernetes       Python         161  Kubernetes + Python
15         AWS        Azure         156          AWS + Azure
16       Linux       Python         156       Linux + Python
17         Git       Python         152         Git + Python
18       React   TypeScript         146   React + TypeScript
19         Git         Java         144           Git + Java

In [142]:
top_15_skill_pairs = (
    skill_pairs
    .head(15)
    .sort_values("job_offers")
)

fig = px.bar(
    top_15_skill_pairs,
    x="job_offers",
    y="skill_pair",
    orientation="h",
    text="job_offers",
    title="Most Common Technology Combinations",
    labels={
        "job_offers": "Number of job offers",
        "skill_pair": "Technology combination",
    },
)

fig.update_traces(
    textposition="outside",
    cliponaxis=False,
)

fig.update_layout(
    showlegend=False,
    height=650,
    yaxis_title=None,
    margin=dict(
        l=130,
        r=70,
        t=70,
        b=50,
    ),
    xaxis_range=[
        0,
        top_15_skill_pairs[
            "job_offers"
        ].max() * 1.15,
    ],
)

fig.show()

### 9.6 Required vs nice-to-have technologies

In [143]:
optional_skills_text = (
    df["nice_to_have"]
    .fillna("")
)

skill_requirement_comparison = []

for skill in skill_candidates:
    pattern = (
        rf"(?<!\w)"
        rf"{re.escape(skill)}"
        rf"(?!\w)"
    )

    required_count = (
        df["required_skills"]
        .fillna("")
        .str.contains(
            pattern,
            case=False,
            regex=True,
        )
        .sum()
    )

    optional_count = (
        optional_skills_text
        .str.contains(
            pattern,
            case=False,
            regex=True,
        )
        .sum()
    )

    skill_requirement_comparison.append({
        "skill": skill,
        "Required": required_count,
        "Nice to have": optional_count,
    })

In [144]:
skill_requirement_comparison = (
    pd.DataFrame(
        skill_requirement_comparison
    )
)

skill_requirement_comparison[
    "total_mentions"
] = (
    skill_requirement_comparison["Required"]
    + skill_requirement_comparison["Nice to have"]
)

top_skill_requirement_comparison = (
    skill_requirement_comparison
    .sort_values(
        "total_mentions",
        ascending=False,
    )
    .head(15)
)

In [145]:
skill_requirement_plot = (
    top_skill_requirement_comparison
    .melt(
        id_vars="skill",
        value_vars=[
            "Required",
            "Nice to have",
        ],
        var_name="requirement_type",
        value_name="job_offers",
    )
)

In [146]:
fig = px.bar(
    skill_requirement_plot,
    x="skill",
    y="job_offers",
    color="requirement_type",
    barmode="group",
    text="job_offers",
    title="Required vs Nice-to-Have Technologies",
    labels={
        "skill": "Technology",
        "job_offers": "Number of job offers",
        "requirement_type": "Requirement type",
    },
)

fig.update_traces(
    textposition="outside",
    cliponaxis=False,
)

fig.update_layout(
    height=550,
    xaxis_tickangle=-35,
    legend_title_text=None,
)

fig.show()

In [147]:
recognized = skill_frequency.loc[skill_frequency['job_offers'].gt(0)].head(3)
show_summary(
    f"Required-skills text available for {df['required_skills'].notna().sum():,} offers; taxonomy size: {len(skill_candidates)}.",
    'Leading matched technologies: ' + ('; '.join(f"{r.skill}: {r.job_offers:,}" for r in recognized.itertuples()) or 'none') + '.',
    salary_summary(salary_by_skill, 'skill'),
    "Skill percentages use offers with required-skills text. Offers can match several technologies, so counts overlap.")

### Calculated summary

- Required-skills text available for 4,569 offers; taxonomy size: 39.
- Leading matched technologies: Python: 1,017; SQL: 972; Java: 755.
- Highest median among included groups: Snowflake: PLN 27,720 (n=64). Differences are descriptive.
- Skill percentages use offers with required-skills text. Offers can match several technologies, so counts overlap.

## 10. Calculated overview and limitations

In [148]:
show_summary(f"This run analyzes {len(df):,} distinct collected offers.",
    distribution_summary('category', 'Category'),
    distribution_summary('experience', 'Experience'),
    f"Salary analysis includes {len(salary_df):,} offers ({len(salary_df)/len(df):.1%}).",
    "These summaries recalculate on each run. Keep reviewed, dated interpretations in separate monthly reports.")

### Calculated summary

- This run analyzes 4,577 distinct collected offers.
- Category: most frequent reported value(s): Backend; 802 offers each (17.5% of all offers). Missing: 0.
- Experience: most frequent reported value(s): Senior; 2,451 offers each (53.6% of all offers). Missing: 84.
- Salary analysis includes 3,223 offers (70.4%).
- These summaries recalculate on each run. Keep reviewed, dated interpretations in separate monthly reports.

### Limitations

- This cumulative dataset does not describe currently active vacancies, publication dates, hires or the whole Polish IT labour market.
- Coverage, collection frequency, gaps and failed requests affect counts. Initial bulk collection is not comparable to subsequent incremental collection. Raw monthly counts alone cannot measure market growth.
- Known URLs are skipped during normal collection. Refreshes and cleaning updates can overwrite records; this table is not a versioned historical snapshot.
- Recruiters may list jobs for multiple clients. Company counts do not measure internal hiring or company size.
- Missing and incorrectly entered data can bias comparisons. Missingness is reported separately.
- Salary analysis follows preparation eligibility flags. Excluded counts are calculated above; excluded offers remain in the dataset.
- Normalization uses fixed currency rates and working-time assumptions from preparation. These are approximate amounts, not current exchange-rate conversions; review the policy before interpreting differences over time.
- B2B and employment-contract amounts differ in tax treatment, benefits and paid leave. Salary disclosure may differ by experience and other groups.
- Remote and Missing locations are excluded from city comparisons; prepared labels may simplify multi-location offers.
- Minimum sample sizes are stated in individual comparisons. Descriptive rankings do not establish statistical significance or causation.
- Skills use an explicit taxonomy, not every possible technology. Whitespace-separated text loses original tag boundaries. Overlapping names and unrecognized aliases can affect counts.
- Offers can match several technologies and both required and optional skills; percentages do not sum to 100%.

### Reporting workflow

Re-run this notebook after successful database updates. Review quality and coverage before interpreting charts. Monthly reports should state the retrieval period and collection coverage, preserve their input snapshot, and contain reviewed interpretation. Preserve the August notebook separately.