In [1]:
from pathlib import Path
import sys
import pandas as pd

PROJECT_ROOT = Path.cwd().parent
SRC_PATH = PROJECT_ROOT / "src"

if str(SRC_PATH) not in sys.path:
    sys.path.insert(0, str(SRC_PATH))

from nfj import (
    collect_job_urls,
    scrape_jobs,
    scrape_one_job
)

print("PROJECT_ROOT:", PROJECT_ROOT)
print("SRC_PATH:", SRC_PATH)
print("Import OK")

PROJECT_ROOT: G:\pandas\job_market_intelligence
SRC_PATH: G:\pandas\job_market_intelligence\src
Import OK

In [2]:
import nfj

print(
    "collect_job_urls:",
    hasattr(nfj, "collect_job_urls")
)

print(
    "scrape_jobs:",
    hasattr(nfj, "scrape_jobs")
)

print(
    "scrape_one_job:",
    hasattr(nfj, "scrape_one_job")
)

collect_job_urls: True
scrape_jobs: True
scrape_one_job: True

In [3]:
df_urls, df_stats = collect_job_urls(
    categories=["data"],
    max_pages_per_category=2,
    delay=1.0,
    headless=False
)

======================================================================
KATEGORIA: data
======================================================================

Strona 1:
https://nofluffjobs.com/pl/data?page=1
URL-i na stronie: 20
Nowych w kategorii: 20
Unikalnych w kategorii: 20
Łącznie globalnie: 20

Strona 2:
https://nofluffjobs.com/pl/data?page=2
URL-i na stronie: 40
Nowych w kategorii: 20
Unikalnych w kategorii: 40
Łącznie globalnie: 40

======================================================================
ZBIERANIE URL-I ZAKOŃCZONE
======================================================================
Łącznie unikalnych URL-i: 40

Statystyki:
  category  category_urls  new_global_urls  total_urls
0     data             40               40          40

Zapisano URL-e:
G:\pandas\job_market_intelligence\data\raw\nofluff_it_urls.csv

In [4]:
print("Amount URL-s:", len(df_urls))

display(df_urls.head())

display(df_stats)

Amount URL-s: 40

                                                 url
0  https://nofluffjobs.com/pl/job/architekt-danyc...
1  https://nofluffjobs.com/pl/job/architekt-danyc...
2  https://nofluffjobs.com/pl/job/azure-data-plat...
3  https://nofluffjobs.com/pl/job/business-analys...
4  https://nofluffjobs.com/pl/job/data-analyst-ew...

  category  category_urls  new_global_urls  total_urls
0     data             40               40          40

In [5]:
print("Amount URL-i:", len(df_urls))

display(df_urls.head())

display(df_stats)

Amount URL-i: 40

                                                 url
0  https://nofluffjobs.com/pl/job/architekt-danyc...
1  https://nofluffjobs.com/pl/job/architekt-danyc...
2  https://nofluffjobs.com/pl/job/azure-data-plat...
3  https://nofluffjobs.com/pl/job/business-analys...
4  https://nofluffjobs.com/pl/job/data-analyst-ew...

  category  category_urls  new_global_urls  total_urls
0     data             40               40          40

In [6]:
print(
    "Duplicated URL:",
    df_urls["url"].duplicated().sum()
)

Duplicated URL: 0

In [7]:
df_test = scrape_jobs(
    max_jobs=5,
    delay=1.0,
    headless=False
)

URL-i do sprawdzenia: 5
Już pobranych: 5

PermissionError: [Errno 13] Permission denied: 'G:\\pandas\\job_market_intelligence\\data\\raw\\nofluff_it_jobs.csv'

In [ ]:
df_test

In [ ]:
df_test.columns.tolist()

In [ ]:
columns_to_check = [
    "title",
    "company",
    "category",
    "experience",
    "experience_years_min",
    "workplace",
    "job_locations",
    "salary_min",
    "salary_max",
    "salary_currency",
    "contract_type"
]

display(
    df_test[columns_to_check]
)

In [ ]:
df_urls, df_stats = collect_job_urls(
    delay=1.0,
    headless=False
)

In [ ]:
from nfj.config import DATA_DIR

TEST_OUTPUT_PATH = DATA_DIR / "nofluff_test_jobs.csv"
TEST_ERROR_PATH = DATA_DIR / "nofluff_test_errors.csv"

df_test = scrape_jobs(
    max_jobs=5,
    delay=1.0,
    headless=False,
    output_path=TEST_OUTPUT_PATH,
    error_path=TEST_ERROR_PATH
)

In [ ]:
print("Liczba ofert:", len(df_test))

display(
    df_test[
        [
            "title",
            "company",
            "category",
            "experience",
            "experience_years_min",
            "workplace",
            "job_locations",
            "salary_min",
            "salary_max",
            "salary_currency",
            "contract_type"
        ]
    ]
)

In [ ]:
df_test.T

In [8]:
df_jobs = scrape_jobs()

URL-i do sprawdzenia: 40
Już pobranych: 5

======================================================================
[6/40]
https://nofluffjobs.com/pl/job/data-analyst-scalo-warszawa-4
OK: Data Analyst
Company: Scalo
Category: Data

======================================================================
[7/40]
https://nofluffjobs.com/pl/job/data-architect-connectis--warszawa-4
OK: Data Architect
Company: Connectis_
Category: Data

======================================================================
[8/40]
https://nofluffjobs.com/pl/job/data-catalog-documentation-specialist-square-one-resources-remote
OK: Data Catalog & Documentation Specialist
Company: Square One Resources
Category: Data

======================================================================
[9/40]
https://nofluffjobs.com/pl/job/data-engineer-gcp-connectis--warszawa-5
OK: Data Engineer GCP
Company: Connectis_
Category: Data

======================================================================
[10/40]
https://nofluffjobs.com/pl/job/data-governance-expert-upvanta-warszawa
OK: Data Governance Expert
Company: None
Category: Data

======================================================================
[11/40]
https://nofluffjobs.com/pl/job/data-platform-developer-kafka-upvanta-remote
OK: Data Platform Developer (Kafka)
Company: None
Category: Data

======================================================================
[12/40]
https://nofluffjobs.com/pl/job/data-platform-developer-upvanta-wroclaw
OK: Data Platform Developer
Company: None
Category: Data

======================================================================
[13/40]
https://nofluffjobs.com/pl/job/data-product-analyst-snowflake-connectis--remote
OK: Data Product Analyst (Snowflake)
Company: Connectis_
Category: None

======================================================================
[14/40]
https://nofluffjobs.com/pl/job/data-qa-engineer-virtusa-remote
OK: Data QA Engineer
Company: VIRTUSA
Category: Data

======================================================================
[15/40]
https://nofluffjobs.com/pl/job/dlp-operations-analyst-mindbox-krakow
OK: DLP Operations Analyst
Company: None
Category: Data

======================================================================
[16/40]
https://nofluffjobs.com/pl/job/expert-data-engineer-diverse-cg-sp-k--gdansk
OK: Expert Data Engineer
Company: Diverse CG Sp. z o.o. Sp.k.
Category: Data

======================================================================
[17/40]
https://nofluffjobs.com/pl/job/expert-data-engineer-ework-group-warszawa-1
OK: Expert Data Engineer
Company: Ework Group
Category: Data

======================================================================
[18/40]
https://nofluffjobs.com/pl/job/ey-gds-poland-nextgen-talent-internship-junior-ai-automation-developer-ey-katowice
OK: EY GDS Poland NextGen Talent Internship - Junior AI Automation Developer
Company: EY
Category: Data

======================================================================
[19/40]
https://nofluffjobs.com/pl/job/ey-gds-poland-nextgen-talent-internship-junior-business-intelligence-consultant-ey-katowice
OK: EY GDS Poland NextGen Talent Internship - Junior Business Intelligence Consultant
Company: EY
Category: None

======================================================================
[20/40]
https://nofluffjobs.com/pl/job/hr-data-analyst-antal-wroclaw
OK: HR Data Analyst
Company: Antal
Category: None

======================================================================
[21/40]
https://nofluffjobs.com/pl/job/inzynier-ka-danych-avenga-agencja-pracy-nr-kraz-8448-warszawa
OK: Inżynier/ka Danych
Company: None
Category: Data

======================================================================
[22/40]
https://nofluffjobs.com/pl/job/it-business-analyst-k-m-k-m-astek-polska-warszawa-2
OK: IT Business Analyst (K/M) K/M
Company: None
Category: Data

======================================================================
[23/40]
https://nofluffjobs.com/pl/job/lead-data-engineer-streaming-real-time-data-platform-banank-pl-remote
OK: Lead Data Engineer (Streaming & Real-Time Data Platform)
Company: None
Category: Python, Data

======================================================================
[24/40]
https://nofluffjobs.com/pl/job/machine-learning-engineer-team-leader-xebia-warszawa-1
OK: Machine Learning Engineer, Team Leader
Company: Xebia sp. z o.o.
Category: Python, Data

======================================================================
[25/40]
https://nofluffjobs.com/pl/job/microsoft-fabric-power-bi-data-modeling-specialist-square-one-resources-remote
OK: Microsoft Fabric & Power BI Data Modeling Specialist
Company: Square One Resources
Category: Data

======================================================================
[26/40]
https://nofluffjobs.com/pl/job/ms-fabric-power-bi-data-specialist-german-speking-enterprise-finance-sap-polcode-remote
OK: MS Fabric & Power BI Data Specialist (German-speking) | Enterprise Finance & SAP
Company: Polcode
Category: None

======================================================================
[27/40]
https://nofluffjobs.com/pl/job/performance-analyst-cloud-technologies-warszawa
OK: Performance Analyst
Company: Cloud Technologies
Category: None

======================================================================
[28/40]
https://nofluffjobs.com/pl/job/power-platform-bi-specialist-link-group-remote
OK: Power Platform & BI Specialist
Company: Link Group
Category: None

======================================================================
[29/40]
https://nofluffjobs.com/pl/job/private-cloud-pmo-officer-mindbox-krakow
OK: Private Cloud PMO Officer
Company: None
Category: Data

======================================================================
[30/40]
https://nofluffjobs.com/pl/job/programista-baz-danych-ms-sql-f-m-astek-polska-warszawa
OK: Programista Baz Danych MS SQL (F/M)
Company: None
Category: Data

PermissionError: [Errno 13] Permission denied: 'G:\\pandas\\job_market_intelligence\\data\\raw\\nofluff_it_jobs.csv'

In [9]:
from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd().parent
SRC_PATH = PROJECT_ROOT / "src"

if str(SRC_PATH) not in sys.path:
    sys.path.insert(0, str(SRC_PATH))

from nfj import scrape_jobs
from nfj.config import DATA_DIR

print("Import OK")

Import OK

In [10]:
TEST_OUTPUT_PATH = DATA_DIR / "nofluff_test_jobs_v3.csv"
TEST_ERROR_PATH = DATA_DIR / "nofluff_test_errors_v3.csv"

df_test = scrape_jobs(
    max_jobs=5,
    delay=1.0,
    headless=False,
    output_path=TEST_OUTPUT_PATH,
    error_path=TEST_ERROR_PATH
)

URL-i do sprawdzenia: 5
Już pobranych: 0

======================================================================
[1/5]
https://nofluffjobs.com/pl/job/architekt-danych-tech-lead-data-platform-praca-hybrydowa-moondigo-warszawa
OK: Architekt Danych / Tech Lead Data Platform (praca hybrydowa)
Company: Moondigo Sp. z o.o.
Category: Data

======================================================================
[2/5]
https://nofluffjobs.com/pl/job/architekt-danych-tech-lead-k-m-astek-polska-warszawa
OK: Architekt Danych / Tech Lead K/M
Company: None
Category: Data

======================================================================
[3/5]
https://nofluffjobs.com/pl/job/azure-data-platform-engineer-m-f-stackmine-remote
OK: Azure Data Platform Engineer [M/F]
Company: Stackmine
Category: Data

======================================================================
[4/5]
https://nofluffjobs.com/pl/job/business-analyst-mindbox-krakow-26
OK: Business Analyst
Company: None
Category: Data

======================================================================
[5/5]
https://nofluffjobs.com/pl/job/data-analyst-ework-group-gdansk-4
OK: Data Analyst
Company: Ework Group
Category: Data

======================================================================
SCRAPING ZAKOŃCZONY
======================================================================
Łącznie ofert: 5
Nowo pobranych: 5
Błędów: 0

CSV:
G:\pandas\job_market_intelligence\data\raw\nofluff_test_jobs_v3.csv

In [11]:
df_test.T

,0,1,2,3,4
job_id,architekt-danych-tech-lead-data-platform-praca...,architekt-danych-tech-lead-k-m-astek-polska-wa...,azure-data-platform-engineer-m-f-stackmine-remote,business-analyst-mindbox-krakow-26,data-analyst-ework-group-gdansk-4
url,https://nofluffjobs.com/pl/job/architekt-danyc...,https://nofluffjobs.com/pl/job/architekt-danyc...,https://nofluffjobs.com/pl/job/azure-data-plat...,https://nofluffjobs.com/pl/job/business-analys...,https://nofluffjobs.com/pl/job/data-analyst-ew...
title,Architekt Danych / Tech Lead Data Platform (pr...,Architekt Danych / Tech Lead K/M,Azure Data Platform Engineer [M/F],Business Analyst,Data Analyst
category,Data,Data,Data,Data,Data
experience,Senior,Mid,Mid,Senior,Senior
experience_years_min,10.0,10.0,NaN,5.0,NaN
workplace,Hybrid,Hybrid,Remote,Hybrid,Hybrid
job_locations,None,None,None,None,None
company,Moondigo Sp. z o.o.,None,Stackmine,None,Ework Group
company_size,10 - 49,None,50 - 249,None,250 - 499
company_founded,2023.0,NaN,2021.0,NaN,2015.0
company_locations,Warsaw,None,Katowice,None,Warszawa
salary_min,28560,25200,26880,21000,23520
salary_max,31920,33600,32760,25200,26880
salary_currency,PLN,PLN,PLN,PLN,PLN
contract_type,None,B2B,None,B2B,None
required_skills,Azure SQL Medallion Java CI/CD Data engineerin...,Data engineering SQL Big Data Microsoft Azure ...,Azure Microsoft Fabric Angielski (C1) Polski (C1),Business analysis Databricks Power BI Data map...,SQL Python Data management Data analysis Angie...
nice_to_have,Event-driven architecture DDD ML AI,None,None,Agile Cybersecurity GitHub Audit,Data migration Governance
requirements,"Minimum 7–10 lat doświadczenia w IT, w tym 3–5...",Posiadasz solidne doświadczenie: Masz min. 7–1...,Min. 6-letnie doświadczenie na podobnym stanow...,Oryginalny tekst. Pokaż tłumaczenie 5+ years o...,✔️Must-have knowledge and experience: Proven e...
offer_description,Poszukujemy doświadczonego Architekta Danych /...,None,Projekt obejmuje modernizację oraz migrację is...,Oryginalny tekst. Pokaż tłumaczenie At Mindbox...,None
responsibilities,Projektowanie i rozwój architektury Cloud Data...,Projektowanie i rozwój platformy: Tworzenie ar...,Udział w warsztatach discovery oraz analizie i...,Oryginalny tekst. Pokaż tłumaczenie Analyse an...,Oryginalny tekst. Pokaż tłumaczenie Supporting...
valid_until,30.08.2026,05.09.2026,06.09.2026,11.09.2026,10.09.2026
start_date,ASAP,ASAP,ASAP,None,ASAP
scraped_at,2026-08-13 19:32:07,2026-08-13 19:32:09,2026-08-13 19:32:11,2026-08-13 19:32:13,2026-08-13 19:32:16

In [1]:
from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd().parent
SRC_PATH = PROJECT_ROOT / "src"

if str(SRC_PATH) not in sys.path:
    sys.path.insert(0, str(SRC_PATH))

from nfj import scrape_jobs
from nfj.config import DATA_DIR

In [2]:
TEST_OUTPUT_PATH = DATA_DIR / "nofluff_test_jobs_v4.csv"
TEST_ERROR_PATH = DATA_DIR / "nofluff_test_errors_v4.csv"

df_test = scrape_jobs(
    max_jobs=5,
    delay=1.0,
    headless=False,
    output_path=TEST_OUTPUT_PATH,
    error_path=TEST_ERROR_PATH
)

URL-i do sprawdzenia: 5
Już pobranych: 0

======================================================================
[1/5]
https://nofluffjobs.com/pl/job/architekt-danych-tech-lead-data-platform-praca-hybrydowa-moondigo-warszawa
OK: Architekt Danych / Tech Lead Data Platform (praca hybrydowa)
Company: Moondigo Sp. z o.o.
Category: Data

======================================================================
[2/5]
https://nofluffjobs.com/pl/job/architekt-danych-tech-lead-k-m-astek-polska-warszawa
OK: Architekt Danych / Tech Lead K/M
Company: None
Category: Data

======================================================================
[3/5]
https://nofluffjobs.com/pl/job/azure-data-platform-engineer-m-f-stackmine-remote
OK: Azure Data Platform Engineer [M/F]
Company: Stackmine
Category: Data

======================================================================
[4/5]
https://nofluffjobs.com/pl/job/business-analyst-mindbox-krakow-26
OK: Business Analyst
Company: None
Category: Data

======================================================================
[5/5]
https://nofluffjobs.com/pl/job/data-analyst-ework-group-gdansk-4
OK: Data Analyst
Company: Ework Group
Category: Data

======================================================================
SCRAPING ZAKOŃCZONY
======================================================================
Łącznie ofert: 5
Nowo pobranych: 5
Błędów: 0

CSV:
G:\pandas\job_market_intelligence\data\raw\nofluff_test_jobs_v4.csv

In [3]:
df_test.T

,0,1,2,3,4
job_id,architekt-danych-tech-lead-data-platform-praca...,architekt-danych-tech-lead-k-m-astek-polska-wa...,azure-data-platform-engineer-m-f-stackmine-remote,business-analyst-mindbox-krakow-26,data-analyst-ework-group-gdansk-4
url,https://nofluffjobs.com/pl/job/architekt-danyc...,https://nofluffjobs.com/pl/job/architekt-danyc...,https://nofluffjobs.com/pl/job/azure-data-plat...,https://nofluffjobs.com/pl/job/business-analys...,https://nofluffjobs.com/pl/job/data-analyst-ew...
title,Architekt Danych / Tech Lead Data Platform (pr...,Architekt Danych / Tech Lead K/M,Azure Data Platform Engineer [M/F],Business Analyst,Data Analyst
category,Data,Data,Data,Data,Data
experience,Senior,Mid,Mid,Senior,Senior
experience_years_min,7.0,7.0,6.0,5.0,NaN
workplace,Hybrid,Hybrid,Remote,Hybrid,Hybrid
job_locations,Warszawa,Warszawa,None,Kraków,Gdańsk
company,Moondigo Sp. z o.o.,None,Stackmine,None,Ework Group
company_size,10 - 49,None,50 - 249,None,250 - 499
company_founded,2023.0,NaN,2021.0,NaN,2015.0
company_locations,Warsaw,None,Katowice,None,Warszawa
salary_min,28560,25200,26880,21000,23520
salary_max,31920,33600,32760,25200,26880
salary_currency,PLN,PLN,PLN,PLN,PLN
contract_type,B2B,B2B,B2B,"B2B, Umowa o pracę",B2B
required_skills,Azure SQL Medallion Java CI/CD Data engineerin...,Data engineering SQL Big Data Microsoft Azure ...,Azure Microsoft Fabric Angielski (C1) Polski (C1),Business analysis Databricks Power BI Data map...,SQL Python Data management Data analysis Angie...
nice_to_have,Event-driven architecture DDD ML AI,None,None,Agile Cybersecurity GitHub Audit,Data migration Governance
requirements,"Minimum 7–10 lat doświadczenia w IT, w tym 3–5...",Posiadasz solidne doświadczenie: Masz min. 7–1...,Min. 6-letnie doświadczenie na podobnym stanow...,Oryginalny tekst. Pokaż tłumaczenie 5+ years o...,✔️Must-have knowledge and experience: Proven e...
offer_description,Poszukujemy doświadczonego Architekta Danych /...,None,Projekt obejmuje modernizację oraz migrację is...,Oryginalny tekst. Pokaż tłumaczenie At Mindbox...,None
responsibilities,Projektowanie i rozwój architektury Cloud Data...,Projektowanie i rozwój platformy: Tworzenie ar...,Udział w warsztatach discovery oraz analizie i...,Oryginalny tekst. Pokaż tłumaczenie Analyse an...,Oryginalny tekst. Pokaż tłumaczenie Supporting...
valid_until,30.08.2026,05.09.2026,06.09.2026,11.09.2026,10.09.2026
start_date,ASAP,ASAP,ASAP,None,ASAP
scraped_at,2026-08-13 19:37:38,2026-08-13 19:37:40,2026-08-13 19:37:42,2026-08-13 19:37:45,2026-08-13 19:37:47

In [1]:
from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd().parent
SRC_PATH = PROJECT_ROOT / "src"

if str(SRC_PATH) not in sys.path:
    sys.path.insert(0, str(SRC_PATH))

from nfj import scrape_jobs
from nfj.config import DATA_DIR

In [3]:
TEST_OUTPUT_PATH = DATA_DIR / "nofluff_test_jobs_v5.csv"
TEST_ERROR_PATH = DATA_DIR / "nofluff_test_errors_v5.csv"

df_test = scrape_jobs(
    max_jobs=5,
    delay=1.0,
    headless=False,
    output_path=TEST_OUTPUT_PATH,
    error_path=TEST_ERROR_PATH
)

URL-i do sprawdzenia: 5
Już pobranych: 0

======================================================================
[1/5]
https://nofluffjobs.com/pl/job/architekt-danych-tech-lead-data-platform-praca-hybrydowa-moondigo-warszawa
OK: Architekt Danych / Tech Lead Data Platform (praca hybrydowa)
Company: Moondigo Sp. z o.o.
Category: Data

======================================================================
[2/5]
https://nofluffjobs.com/pl/job/architekt-danych-tech-lead-k-m-astek-polska-warszawa
OK: Architekt Danych / Tech Lead K/M
Company: None
Category: Data

======================================================================
[3/5]
https://nofluffjobs.com/pl/job/azure-data-platform-engineer-m-f-stackmine-remote
OK: Azure Data Platform Engineer [M/F]
Company: Stackmine
Category: Data

======================================================================
[4/5]
https://nofluffjobs.com/pl/job/business-analyst-mindbox-krakow-26
OK: Business Analyst
Company: None
Category: Data

======================================================================
[5/5]
https://nofluffjobs.com/pl/job/data-analyst-ework-group-gdansk-4
OK: Data Analyst
Company: Ework Group
Category: Data

======================================================================
SCRAPING ZAKOŃCZONY
======================================================================
Łącznie ofert: 5
Nowo pobranych: 5
Błędów: 0

CSV:
G:\pandas\job_market_intelligence\data\raw\nofluff_test_jobs_v5.csv

In [4]:
df_test.T

,0,1,2,3,4
job_id,architekt-danych-tech-lead-data-platform-praca...,architekt-danych-tech-lead-k-m-astek-polska-wa...,azure-data-platform-engineer-m-f-stackmine-remote,business-analyst-mindbox-krakow-26,data-analyst-ework-group-gdansk-4
url,https://nofluffjobs.com/pl/job/architekt-danyc...,https://nofluffjobs.com/pl/job/architekt-danyc...,https://nofluffjobs.com/pl/job/azure-data-plat...,https://nofluffjobs.com/pl/job/business-analys...,https://nofluffjobs.com/pl/job/data-analyst-ew...
title,Architekt Danych / Tech Lead Data Platform (pr...,Architekt Danych / Tech Lead K/M,Azure Data Platform Engineer [M/F],Business Analyst,Data Analyst
category,Data,Data,Data,Data,Data
experience,Senior,Mid,Mid,Senior,Senior
experience_years_min,7.0,7.0,6.0,5.0,NaN
workplace,Hybrid,Hybrid,Remote,Hybrid,Hybrid
job_locations,Warszawa,Warszawa,None,Kraków,Gdańsk
company,Moondigo Sp. z o.o.,None,Stackmine,None,Ework Group
company_size,10 - 49,None,50 - 249,None,250 - 499
company_founded,2023.0,NaN,2021.0,NaN,2015.0
company_locations,Warsaw,None,Katowice,None,Warszawa
salary_min,28560,25200,26880,21000,23520
salary_max,31920,33600,32760,25200,26880
salary_currency,PLN,PLN,PLN,PLN,PLN
contract_type,B2B,B2B,B2B,"B2B, Umowa o pracę",B2B
required_skills,Azure SQL Medallion Java CI/CD Data engineerin...,Data engineering SQL Big Data Microsoft Azure ...,Azure Microsoft Fabric Angielski (C1) Polski (C1),Business analysis Databricks Power BI Data map...,SQL Python Data management Data analysis Angie...
nice_to_have,Event-driven architecture DDD ML AI,None,None,Agile Cybersecurity GitHub Audit,Data migration Governance
requirements,"Minimum 7–10 lat doświadczenia w IT, w tym 3–5...",Posiadasz solidne doświadczenie: Masz min. 7–1...,Min. 6-letnie doświadczenie na podobnym stanow...,Oryginalny tekst. Pokaż tłumaczenie 5+ years o...,✔️Must-have knowledge and experience: Proven e...
offer_description,Poszukujemy doświadczonego Architekta Danych /...,None,Projekt obejmuje modernizację oraz migrację is...,Oryginalny tekst. Pokaż tłumaczenie At Mindbox...,None
responsibilities,Projektowanie i rozwój architektury Cloud Data...,Projektowanie i rozwój platformy: Tworzenie ar...,Udział w warsztatach discovery oraz analizie i...,Oryginalny tekst. Pokaż tłumaczenie Analyse an...,Oryginalny tekst. Pokaż tłumaczenie Supporting...
valid_until,30.08.2026,05.09.2026,06.09.2026,11.09.2026,10.09.2026
start_date,ASAP,ASAP,ASAP,None,ASAP
scraped_at,2026-08-13 19:46:22,2026-08-13 19:46:24,2026-08-13 19:46:26,2026-08-13 19:46:28,2026-08-13 19:46:31

In [1]:
from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd().parent
SRC_PATH = PROJECT_ROOT / "src"

if str(SRC_PATH) not in sys.path:
    sys.path.insert(0, str(SRC_PATH))

from nfj import scrape_jobs
from nfj.config import DATA_DIR

In [2]:
TEST_OUTPUT_PATH = DATA_DIR / "nofluff_test_jobs_v6.csv"
TEST_ERROR_PATH = DATA_DIR / "nofluff_test_errors_v6.csv"

df_test = scrape_jobs(
    max_jobs=5,
    delay=1.0,
    headless=False,
    output_path=TEST_OUTPUT_PATH,
    error_path=TEST_ERROR_PATH
)

URL-i do sprawdzenia: 5
Już pobranych: 0

======================================================================
[1/5]
https://nofluffjobs.com/pl/job/architekt-danych-tech-lead-data-platform-praca-hybrydowa-moondigo-warszawa
OK: Architekt Danych / Tech Lead Data Platform (praca hybrydowa)
Company: Moondigo Sp. z o.o.
Category: Data

======================================================================
[2/5]
https://nofluffjobs.com/pl/job/architekt-danych-tech-lead-k-m-astek-polska-warszawa
OK: Architekt Danych / Tech Lead K/M
Company: Architekt Danych / Tech Lead K/M
Category: Data

======================================================================
[3/5]
https://nofluffjobs.com/pl/job/azure-data-platform-engineer-m-f-stackmine-remote
OK: Azure Data Platform Engineer [M/F]
Company: Stackmine
Category: Data

======================================================================
[4/5]
https://nofluffjobs.com/pl/job/business-analyst-mindbox-krakow-26
OK: Business Analyst
Company: Business Analyst
Category: Data

======================================================================
[5/5]
https://nofluffjobs.com/pl/job/data-analyst-ework-group-gdansk-4
OK: Data Analyst
Company: Ework Group
Category: Data

======================================================================
SCRAPING ZAKOŃCZONY
======================================================================
Łącznie ofert: 5
Nowo pobranych: 5
Błędów: 0

CSV:
G:\pandas\job_market_intelligence\data\raw\nofluff_test_jobs_v6.csv

In [3]:
df_test.T

,0,1,2,3,4
job_id,architekt-danych-tech-lead-data-platform-praca...,architekt-danych-tech-lead-k-m-astek-polska-wa...,azure-data-platform-engineer-m-f-stackmine-remote,business-analyst-mindbox-krakow-26,data-analyst-ework-group-gdansk-4
url,https://nofluffjobs.com/pl/job/architekt-danyc...,https://nofluffjobs.com/pl/job/architekt-danyc...,https://nofluffjobs.com/pl/job/azure-data-plat...,https://nofluffjobs.com/pl/job/business-analys...,https://nofluffjobs.com/pl/job/data-analyst-ew...
title,Architekt Danych / Tech Lead Data Platform (pr...,Architekt Danych / Tech Lead K/M,Azure Data Platform Engineer [M/F],Business Analyst,Data Analyst
category,Data,Data,Data,Data,Data
experience,Senior,Mid,Mid,Senior,Senior
experience_years_min,7.0,7.0,6.0,5.0,NaN
workplace,Hybrid,Hybrid,Remote,Hybrid,Hybrid
job_locations,Warszawa,Warszawa,None,Kraków,Gdańsk
company,Moondigo Sp. z o.o.,Architekt Danych / Tech Lead K/M,Stackmine,Business Analyst,Ework Group
company_size,10 - 49,None,50 - 249,None,250 - 499
company_founded,2023.0,NaN,2021.0,NaN,2015.0
company_locations,Warsaw,None,Katowice,None,Warszawa
salary_min,28560,25200,26880,21000,23520
salary_max,31920,33600,32760,25200,26880
salary_currency,PLN,PLN,PLN,PLN,PLN
contract_type,B2B,B2B,B2B,"B2B, Umowa o pracę",B2B
required_skills,Azure SQL Medallion Java CI/CD Data engineerin...,Data engineering SQL Big Data Microsoft Azure ...,Azure Microsoft Fabric Angielski (C1) Polski (C1),Business analysis Databricks Power BI Data map...,SQL Python Data management Data analysis Angie...
nice_to_have,Event-driven architecture DDD ML AI,None,None,Agile Cybersecurity GitHub Audit,Data migration Governance
requirements,"Minimum 7–10 lat doświadczenia w IT, w tym 3–5...",Posiadasz solidne doświadczenie: Masz min. 7–1...,Min. 6-letnie doświadczenie na podobnym stanow...,Oryginalny tekst. Pokaż tłumaczenie 5+ years o...,✔️Must-have knowledge and experience: Proven e...
offer_description,Poszukujemy doświadczonego Architekta Danych /...,None,Projekt obejmuje modernizację oraz migrację is...,Oryginalny tekst. Pokaż tłumaczenie At Mindbox...,None
responsibilities,Projektowanie i rozwój architektury Cloud Data...,Projektowanie i rozwój platformy: Tworzenie ar...,Udział w warsztatach discovery oraz analizie i...,Oryginalny tekst. Pokaż tłumaczenie Analyse an...,Oryginalny tekst. Pokaż tłumaczenie Supporting...
valid_until,30.08.2026,05.09.2026,06.09.2026,11.09.2026,10.09.2026
start_date,ASAP,ASAP,ASAP,None,ASAP
scraped_at,2026-08-13 19:49:46,2026-08-13 19:49:48,2026-08-13 19:49:50,2026-08-13 19:49:52,2026-08-13 19:49:55

In [4]:
from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd().parent
SRC_PATH = PROJECT_ROOT / "src"

if str(SRC_PATH) not in sys.path:
    sys.path.insert(0, str(SRC_PATH))

from nfj import scrape_jobs
from nfj.config import DATA_DIR

In [6]:
TEST_OUTPUT_PATH = DATA_DIR / "nofluff_test_jobs_v7.csv"
TEST_ERROR_PATH = DATA_DIR / "nofluff_test_errors_v7.csv"

df_test = scrape_jobs(
    max_jobs=5,
    delay=1.0,
    headless=False,
    output_path=TEST_OUTPUT_PATH,
    error_path=TEST_ERROR_PATH
)

URL-i do sprawdzenia: 5
Już pobranych: 0

======================================================================
[1/5]
https://nofluffjobs.com/pl/job/architekt-danych-tech-lead-data-platform-praca-hybrydowa-moondigo-warszawa
OK: Architekt Danych / Tech Lead Data Platform (praca hybrydowa)
Company: Moondigo Sp. z o.o.
Category: Data

======================================================================
[2/5]
https://nofluffjobs.com/pl/job/architekt-danych-tech-lead-k-m-astek-polska-warszawa
OK: Architekt Danych / Tech Lead K/M
Company: Architekt Danych / Tech Lead K/M
Category: Data

======================================================================
[3/5]
https://nofluffjobs.com/pl/job/azure-data-platform-engineer-m-f-stackmine-remote
OK: Azure Data Platform Engineer [M/F]
Company: Stackmine
Category: Data

======================================================================
[4/5]
https://nofluffjobs.com/pl/job/business-analyst-mindbox-krakow-26
OK: Business Analyst
Company: Business Analyst
Category: Data

======================================================================
[5/5]
https://nofluffjobs.com/pl/job/data-analyst-ework-group-gdansk-4
OK: Data Analyst
Company: Ework Group
Category: Data

======================================================================
SCRAPING ZAKOŃCZONY
======================================================================
Łącznie ofert: 5
Nowo pobranych: 5
Błędów: 0

CSV:
G:\pandas\job_market_intelligence\data\raw\nofluff_test_jobs_v7.csv

In [7]:
df_test.T

,0,1,2,3,4
job_id,architekt-danych-tech-lead-data-platform-praca...,architekt-danych-tech-lead-k-m-astek-polska-wa...,azure-data-platform-engineer-m-f-stackmine-remote,business-analyst-mindbox-krakow-26,data-analyst-ework-group-gdansk-4
url,https://nofluffjobs.com/pl/job/architekt-danyc...,https://nofluffjobs.com/pl/job/architekt-danyc...,https://nofluffjobs.com/pl/job/azure-data-plat...,https://nofluffjobs.com/pl/job/business-analys...,https://nofluffjobs.com/pl/job/data-analyst-ew...
title,Architekt Danych / Tech Lead Data Platform (pr...,Architekt Danych / Tech Lead K/M,Azure Data Platform Engineer [M/F],Business Analyst,Data Analyst
category,Data,Data,Data,Data,Data
experience,Senior,Mid,Mid,Senior,Senior
experience_years_min,7.0,7.0,6.0,5.0,NaN
workplace,Hybrid,Hybrid,Remote,Hybrid,Hybrid
job_locations,Warszawa,Warszawa,None,Kraków,Gdańsk
company,Moondigo Sp. z o.o.,Architekt Danych / Tech Lead K/M,Stackmine,Business Analyst,Ework Group
company_size,10 - 49,None,50 - 249,None,250 - 499
company_founded,2023.0,NaN,2021.0,NaN,2015.0
company_locations,Warsaw,None,Katowice,None,Warszawa
salary_min,28560,25200,26880,21000,23520
salary_max,31920,33600,32760,25200,26880
salary_currency,PLN,PLN,PLN,PLN,PLN
contract_type,B2B,B2B,B2B,"B2B, Umowa o pracę",B2B
required_skills,Azure SQL Medallion Java CI/CD Data engineerin...,Data engineering SQL Big Data Microsoft Azure ...,Azure Microsoft Fabric Angielski (C1) Polski (C1),Business analysis Databricks Power BI Data map...,SQL Python Data management Data analysis Angie...
nice_to_have,Event-driven architecture DDD ML AI,None,None,Agile Cybersecurity GitHub Audit,Data migration Governance
requirements,"Minimum 7–10 lat doświadczenia w IT, w tym 3–5...",Posiadasz solidne doświadczenie: Masz min. 7–1...,Min. 6-letnie doświadczenie na podobnym stanow...,Oryginalny tekst. Pokaż tłumaczenie 5+ years o...,✔️Must-have knowledge and experience: Proven e...
offer_description,Poszukujemy doświadczonego Architekta Danych /...,None,Projekt obejmuje modernizację oraz migrację is...,Oryginalny tekst. Pokaż tłumaczenie At Mindbox...,None
responsibilities,Projektowanie i rozwój architektury Cloud Data...,Projektowanie i rozwój platformy: Tworzenie ar...,Udział w warsztatach discovery oraz analizie i...,Oryginalny tekst. Pokaż tłumaczenie Analyse an...,Oryginalny tekst. Pokaż tłumaczenie Supporting...
valid_until,30.08.2026,05.09.2026,06.09.2026,11.09.2026,10.09.2026
start_date,ASAP,ASAP,ASAP,None,ASAP
scraped_at,2026-08-13 19:59:32,2026-08-13 19:59:34,2026-08-13 19:59:36,2026-08-13 19:59:39,2026-08-13 19:59:41

In [1]:
from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd().parent
SRC_PATH = PROJECT_ROOT / "src"

if str(SRC_PATH) not in sys.path:
    sys.path.insert(0, str(SRC_PATH))

from nfj import scrape_jobs
from nfj.config import DATA_DIR

In [3]:
TEST_OUTPUT_PATH = DATA_DIR / "nofluff_test_jobs_v8.csv"
TEST_ERROR_PATH = DATA_DIR / "nofluff_test_errors_v8.csv"

df_test = scrape_jobs(
    max_jobs=5,
    delay=1.0,
    headless=False,
    output_path=TEST_OUTPUT_PATH,
    error_path=TEST_ERROR_PATH
)

URL-i do sprawdzenia: 5
Już pobranych: 0

======================================================================
[1/5]
https://nofluffjobs.com/pl/job/architekt-danych-tech-lead-data-platform-praca-hybrydowa-moondigo-warszawa
OK: Architekt Danych / Tech Lead Data Platform (praca hybrydowa)
Company: Moondigo Sp. z o.o.
Category: Data

======================================================================
[2/5]
https://nofluffjobs.com/pl/job/architekt-danych-tech-lead-k-m-astek-polska-warszawa
OK: Architekt Danych / Tech Lead K/M
Company: ASTEK Polska
Category: Data

======================================================================
[3/5]
https://nofluffjobs.com/pl/job/azure-data-platform-engineer-m-f-stackmine-remote
OK: Azure Data Platform Engineer [M/F]
Company: Stackmine
Category: Data

======================================================================
[4/5]
https://nofluffjobs.com/pl/job/business-analyst-mindbox-krakow-26
OK: Business Analyst
Company: Mindbox Sp. z o.o.
Category: Data

======================================================================
[5/5]
https://nofluffjobs.com/pl/job/data-analyst-ework-group-gdansk-4
OK: Data Analyst
Company: Ework Group
Category: Data

======================================================================
SCRAPING ZAKOŃCZONY
======================================================================
Łącznie ofert: 5
Nowo pobranych: 5
Błędów: 0

CSV:
G:\pandas\job_market_intelligence\data\raw\nofluff_test_jobs_v8.csv

In [4]:
df_test.T

,0,1,2,3,4
job_id,architekt-danych-tech-lead-data-platform-praca...,architekt-danych-tech-lead-k-m-astek-polska-wa...,azure-data-platform-engineer-m-f-stackmine-remote,business-analyst-mindbox-krakow-26,data-analyst-ework-group-gdansk-4
url,https://nofluffjobs.com/pl/job/architekt-danyc...,https://nofluffjobs.com/pl/job/architekt-danyc...,https://nofluffjobs.com/pl/job/azure-data-plat...,https://nofluffjobs.com/pl/job/business-analys...,https://nofluffjobs.com/pl/job/data-analyst-ew...
title,Architekt Danych / Tech Lead Data Platform (pr...,Architekt Danych / Tech Lead K/M,Azure Data Platform Engineer [M/F],Business Analyst,Data Analyst
category,Data,Data,Data,Data,Data
experience,Senior,Mid,Mid,Senior,Senior
experience_years_min,7.0,7.0,6.0,5.0,NaN
workplace,Hybrid,Hybrid,Remote,Hybrid,Hybrid
job_locations,Warszawa,Warszawa,None,Kraków,Gdańsk
company,Moondigo Sp. z o.o.,ASTEK Polska,Stackmine,Mindbox Sp. z o.o.,Ework Group
company_size,10 - 49,None,50 - 249,None,250 - 499
company_founded,2023.0,NaN,2021.0,NaN,2015.0
company_locations,Warsaw,None,Katowice,None,Warszawa
salary_min,28560,25200,26880,21000,23520
salary_max,31920,33600,32760,25200,26880
salary_currency,PLN,PLN,PLN,PLN,PLN
contract_type,B2B,B2B,B2B,"B2B, Umowa o pracę",B2B
required_skills,Azure SQL Medallion Java CI/CD Data engineerin...,Data engineering SQL Big Data Microsoft Azure ...,Azure Microsoft Fabric Angielski (C1) Polski (C1),Business analysis Databricks Power BI Data map...,SQL Python Data management Data analysis Angie...
nice_to_have,Event-driven architecture DDD ML AI,None,None,Agile Cybersecurity GitHub Audit,Data migration Governance
requirements,"Minimum 7–10 lat doświadczenia w IT, w tym 3–5...",Posiadasz solidne doświadczenie: Masz min. 7–1...,Min. 6-letnie doświadczenie na podobnym stanow...,Oryginalny tekst. Pokaż tłumaczenie 5+ years o...,✔️Must-have knowledge and experience: Proven e...
offer_description,Poszukujemy doświadczonego Architekta Danych /...,None,Projekt obejmuje modernizację oraz migrację is...,Oryginalny tekst. Pokaż tłumaczenie At Mindbox...,None
responsibilities,Projektowanie i rozwój architektury Cloud Data...,Projektowanie i rozwój platformy: Tworzenie ar...,Udział w warsztatach discovery oraz analizie i...,Oryginalny tekst. Pokaż tłumaczenie Analyse an...,Oryginalny tekst. Pokaż tłumaczenie Supporting...
valid_until,30.08.2026,05.09.2026,06.09.2026,11.09.2026,10.09.2026
start_date,ASAP,ASAP,ASAP,None,ASAP
scraped_at,2026-08-13 20:05:25,2026-08-13 20:05:27,2026-08-13 20:05:29,2026-08-13 20:05:32,2026-08-13 20:05:34

In [6]:
from nfj import collect_job_urls

df_urls, df_stats = collect_job_urls(
    delay=1.0,
    headless=False
)

======================================================================
KATEGORIA: it
======================================================================

Strona 1:
https://nofluffjobs.com/pl/it?page=1
URL-i na stronie: 20
Nowych w kategorii: 20
Unikalnych w kategorii: 20
Łącznie globalnie: 20

Strona 2:
https://nofluffjobs.com/pl/it?page=2
URL-i na stronie: 40
Nowych w kategorii: 20
Unikalnych w kategorii: 40
Łącznie globalnie: 40

Strona 3:
https://nofluffjobs.com/pl/it?page=3
URL-i na stronie: 60
Nowych w kategorii: 20
Unikalnych w kategorii: 60
Łącznie globalnie: 60

Strona 4:
https://nofluffjobs.com/pl/it?page=4
URL-i na stronie: 80
Nowych w kategorii: 20
Unikalnych w kategorii: 80
Łącznie globalnie: 80

Strona 5:
https://nofluffjobs.com/pl/it?page=5
URL-i na stronie: 100
Nowych w kategorii: 20
Unikalnych w kategorii: 100
Łącznie globalnie: 100

Strona 6:
https://nofluffjobs.com/pl/it?page=6
URL-i na stronie: 85
Nowych w kategorii: 85
Unikalnych w kategorii: 185
Łącznie globalnie: 185

Strona 7:
https://nofluffjobs.com/pl/it?page=7
URL-i na stronie: 0
Nowych w kategorii: 0
Unikalnych w kategorii: 185
Łącznie globalnie: 185
Brak nowych ofert w kategorii - zatrzymuję kategorię.

======================================================================
KATEGORIA: backend
======================================================================

Strona 1:
https://nofluffjobs.com/pl/backend?page=1
URL-i na stronie: 20
Nowych w kategorii: 20
Unikalnych w kategorii: 20
Łącznie globalnie: 205

Strona 2:
https://nofluffjobs.com/pl/backend?page=2
URL-i na stronie: 40
Nowych w kategorii: 20
Unikalnych w kategorii: 40
Łącznie globalnie: 224

Strona 3:
https://nofluffjobs.com/pl/backend?page=3
URL-i na stronie: 60
Nowych w kategorii: 20
Unikalnych w kategorii: 60
Łącznie globalnie: 243

Strona 4:
https://nofluffjobs.com/pl/backend?page=4
URL-i na stronie: 80
Nowych w kategorii: 20
Unikalnych w kategorii: 80
Łącznie globalnie: 263

Strona 5:
https://nofluffjobs.com/pl/backend?page=5
URL-i na stronie: 100
Nowych w kategorii: 20
Unikalnych w kategorii: 100
Łącznie globalnie: 281

Strona 6:
https://nofluffjobs.com/pl/backend?page=6
URL-i na stronie: 100
Nowych w kategorii: 100
Unikalnych w kategorii: 200
Łącznie globalnie: 380

Strona 7:
https://nofluffjobs.com/pl/backend?page=7
URL-i na stronie: 120
Nowych w kategorii: 100
Unikalnych w kategorii: 300
Łącznie globalnie: 474

Strona 8:
https://nofluffjobs.com/pl/backend?page=8
URL-i na stronie: 120
Nowych w kategorii: 100
Unikalnych w kategorii: 400
Łącznie globalnie: 574

Strona 9:
https://nofluffjobs.com/pl/backend?page=9
URL-i na stronie: 120
Nowych w kategorii: 100
Unikalnych w kategorii: 500
Łącznie globalnie: 674

Strona 10:
https://nofluffjobs.com/pl/backend?page=10
Błąd strony 10: Message: stale element reference: stale element not found in the current frame
  (Session info: chrome=151.0.7922.109); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#staleelementreferenceexception
Stacktrace:
	chromedriver!GetHandleVerifier [0x7ff629b6abb5+151b5]
	chromedriver!GetHandleVerifier [0x7ff629b6ac10+15210]
	chromedriver!(No symbol) [0x7ff629695d6d]
	chromedriver!(No symbol) [0x7ff62969dcd1]
	chromedriver!(No symbol) [0x7ff6296a101f]
	chromedriver!(No symbol) [0x7ff62973fe82]
	chromedriver!(No symbol) [0x7ff629719d0a]
	chromedriver!(No symbol) [0x7ff62973ec0b]
	chromedriver!(No symbol) [0x7ff6296e37cc]
	chromedriver!(No symbol) [0x7ff6296e46f3]
	chromedriver!GetHandleVerifier [0x7ff62a18b79b+635d9b]
	chromedriver!GetHandleVerifier [0x7ff62a185ac6+6300c6]
	chromedriver!GetHandleVerifier [0x7ff62a1abcee+6562ee]
	chromedriver!GetHandleVerifier [0x7ff629b88ffe+335fe]
	chromedriver!GetHandleVerifier [0x7ff629b9147c+3ba7c]
	chromedriver!GetHandleVerifier [0x7ff629b74d64+1f364]
	chromedriver!GetHandleVerifier [0x7ff629b74ef4+1f4f4]
	chromedriver!GetHandleVerifier [0x7ff629b57d97+2397]
	KERNEL32!BaseThreadInitThunk [0x7ffceebb257d+1d]
	ntdll!RtlUserThreadStart [0x7ffcef58af08+28]


======================================================================
KATEGORIA: frontend
======================================================================

Strona 1:
https://nofluffjobs.com/pl/frontend?page=1
URL-i na stronie: 20
Nowych w kategorii: 20
Unikalnych w kategorii: 20
Łącznie globalnie: 694

Strona 2:
https://nofluffjobs.com/pl/frontend?page=2
URL-i na stronie: 40
Nowych w kategorii: 20
Unikalnych w kategorii: 40
Łącznie globalnie: 714

Strona 3:
https://nofluffjobs.com/pl/frontend?page=3
URL-i na stronie: 60
Nowych w kategorii: 20
Unikalnych w kategorii: 60
Łącznie globalnie: 734

Strona 4:
https://nofluffjobs.com/pl/frontend?page=4
Błąd strony 4: Message: stale element reference: stale element not found in the current frame
  (Session info: chrome=151.0.7922.109); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#staleelementreferenceexception
Stacktrace:
	chromedriver!GetHandleVerifier [0x7ff629b6abb5+151b5]
	chromedriver!GetHandleVerifier [0x7ff629b6ac10+15210]
	chromedriver!(No symbol) [0x7ff629695d6d]
	chromedriver!(No symbol) [0x7ff62969dcd1]
	chromedriver!(No symbol) [0x7ff6296a101f]
	chromedriver!(No symbol) [0x7ff62973fe82]
	chromedriver!(No symbol) [0x7ff629719d0a]
	chromedriver!(No symbol) [0x7ff62973ec0b]
	chromedriver!(No symbol) [0x7ff6296e37cc]
	chromedriver!(No symbol) [0x7ff6296e46f3]
	chromedriver!GetHandleVerifier [0x7ff62a18b79b+635d9b]
	chromedriver!GetHandleVerifier [0x7ff62a185ac6+6300c6]
	chromedriver!GetHandleVerifier [0x7ff62a1abcee+6562ee]
	chromedriver!GetHandleVerifier [0x7ff629b88ffe+335fe]
	chromedriver!GetHandleVerifier [0x7ff629b9147c+3ba7c]
	chromedriver!GetHandleVerifier [0x7ff629b74d64+1f364]
	chromedriver!GetHandleVerifier [0x7ff629b74ef4+1f4f4]
	chromedriver!GetHandleVerifier [0x7ff629b57d97+2397]
	KERNEL32!BaseThreadInitThunk [0x7ffceebb257d+1d]
	ntdll!RtlUserThreadStart [0x7ffcef58af08+28]


======================================================================
KATEGORIA: fullstack
======================================================================

Strona 1:
https://nofluffjobs.com/pl/fullstack?page=1
URL-i na stronie: 20
Nowych w kategorii: 20
Unikalnych w kategorii: 20
Łącznie globalnie: 754

Strona 2:
https://nofluffjobs.com/pl/fullstack?page=2
URL-i na stronie: 40
Nowych w kategorii: 20
Unikalnych w kategorii: 40
Łącznie globalnie: 774

Strona 3:
https://nofluffjobs.com/pl/fullstack?page=3
Błąd strony 3: Message: stale element reference: stale element not found in the current frame
  (Session info: chrome=151.0.7922.109); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#staleelementreferenceexception
Stacktrace:
	chromedriver!GetHandleVerifier [0x7ff629b6abb5+151b5]
	chromedriver!GetHandleVerifier [0x7ff629b6ac10+15210]
	chromedriver!(No symbol) [0x7ff629695d6d]
	chromedriver!(No symbol) [0x7ff62969dcd1]
	chromedriver!(No symbol) [0x7ff6296a101f]
	chromedriver!(No symbol) [0x7ff62973fe82]
	chromedriver!(No symbol) [0x7ff629719d0a]
	chromedriver!(No symbol) [0x7ff62973ec0b]
	chromedriver!(No symbol) [0x7ff6296e37cc]
	chromedriver!(No symbol) [0x7ff6296e46f3]
	chromedriver!GetHandleVerifier [0x7ff62a18b79b+635d9b]
	chromedriver!GetHandleVerifier [0x7ff62a185ac6+6300c6]
	chromedriver!GetHandleVerifier [0x7ff62a1abcee+6562ee]
	chromedriver!GetHandleVerifier [0x7ff629b88ffe+335fe]
	chromedriver!GetHandleVerifier [0x7ff629b9147c+3ba7c]
	chromedriver!GetHandleVerifier [0x7ff629b74d64+1f364]
	chromedriver!GetHandleVerifier [0x7ff629b74ef4+1f4f4]
	chromedriver!GetHandleVerifier [0x7ff629b57d97+2397]
	KERNEL32!BaseThreadInitThunk [0x7ffceebb257d+1d]
	ntdll!RtlUserThreadStart [0x7ffcef58af08+28]


======================================================================
KATEGORIA: data
======================================================================

Strona 1:
https://nofluffjobs.com/pl/data?page=1
URL-i na stronie: 20
Nowych w kategorii: 20
Unikalnych w kategorii: 20
Łącznie globalnie: 794

Strona 2:
https://nofluffjobs.com/pl/data?page=2
URL-i na stronie: 40
Nowych w kategorii: 20
Unikalnych w kategorii: 40
Łącznie globalnie: 813

Strona 3:
https://nofluffjobs.com/pl/data?page=3
Błąd strony 3: Message: stale element reference: stale element not found in the current frame
  (Session info: chrome=151.0.7922.109); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#staleelementreferenceexception
Stacktrace:
	chromedriver!GetHandleVerifier [0x7ff629b6abb5+151b5]
	chromedriver!GetHandleVerifier [0x7ff629b6ac10+15210]
	chromedriver!(No symbol) [0x7ff629695d6d]
	chromedriver!(No symbol) [0x7ff62969dcd1]
	chromedriver!(No symbol) [0x7ff6296a101f]
	chromedriver!(No symbol) [0x7ff62973fe82]
	chromedriver!(No symbol) [0x7ff629719d0a]
	chromedriver!(No symbol) [0x7ff62973ec0b]
	chromedriver!(No symbol) [0x7ff6296e37cc]
	chromedriver!(No symbol) [0x7ff6296e46f3]
	chromedriver!GetHandleVerifier [0x7ff62a18b79b+635d9b]
	chromedriver!GetHandleVerifier [0x7ff62a185ac6+6300c6]
	chromedriver!GetHandleVerifier [0x7ff62a1abcee+6562ee]
	chromedriver!GetHandleVerifier [0x7ff629b88ffe+335fe]
	chromedriver!GetHandleVerifier [0x7ff629b9147c+3ba7c]
	chromedriver!GetHandleVerifier [0x7ff629b74d64+1f364]
	chromedriver!GetHandleVerifier [0x7ff629b74ef4+1f4f4]
	chromedriver!GetHandleVerifier [0x7ff629b57d97+2397]
	KERNEL32!BaseThreadInitThunk [0x7ffceebb257d+1d]
	ntdll!RtlUserThreadStart [0x7ffcef58af08+28]


======================================================================
KATEGORIA: ai
======================================================================

Strona 1:
https://nofluffjobs.com/pl/ai?page=1
URL-i na stronie: 20
Nowych w kategorii: 20
Unikalnych w kategorii: 20
Łącznie globalnie: 832

Strona 2:
https://nofluffjobs.com/pl/ai?page=2
URL-i na stronie: 40
Nowych w kategorii: 20
Unikalnych w kategorii: 40
Łącznie globalnie: 852

Strona 3:
https://nofluffjobs.com/pl/ai?page=3
URL-i na stronie: 60
Nowych w kategorii: 20
Unikalnych w kategorii: 60
Łącznie globalnie: 872

Strona 4:
https://nofluffjobs.com/pl/ai?page=4
URL-i na stronie: 80
Nowych w kategorii: 20
Unikalnych w kategorii: 80
Łącznie globalnie: 891

Strona 5:
https://nofluffjobs.com/pl/ai?page=5
URL-i na stronie: 100
Nowych w kategorii: 20
Unikalnych w kategorii: 100
Łącznie globalnie: 911

Strona 6:
https://nofluffjobs.com/pl/ai?page=6
URL-i na stronie: 100
Nowych w kategorii: 100
Unikalnych w kategorii: 200
Łącznie globalnie: 1011

Strona 7:
https://nofluffjobs.com/pl/ai?page=7
URL-i na stronie: 0
Nowych w kategorii: 0
Unikalnych w kategorii: 200
Łącznie globalnie: 1011
Brak nowych ofert w kategorii - zatrzymuję kategorię.

======================================================================
KATEGORIA: devops
======================================================================

Strona 1:
https://nofluffjobs.com/pl/devops?page=1
URL-i na stronie: 20
Nowych w kategorii: 20
Unikalnych w kategorii: 20
Łącznie globalnie: 1031

Strona 2:
https://nofluffjobs.com/pl/devops?page=2
URL-i na stronie: 40
Nowych w kategorii: 20
Unikalnych w kategorii: 40
Łącznie globalnie: 1050

Strona 3:
https://nofluffjobs.com/pl/devops?page=3
URL-i na stronie: 60
Nowych w kategorii: 20
Unikalnych w kategorii: 60
Łącznie globalnie: 1069

Strona 4:
https://nofluffjobs.com/pl/devops?page=4
URL-i na stronie: 80
Nowych w kategorii: 20
Unikalnych w kategorii: 80
Łącznie globalnie: 1089

Strona 5:
https://nofluffjobs.com/pl/devops?page=5
URL-i na stronie: 100
Nowych w kategorii: 20
Unikalnych w kategorii: 100
Łącznie globalnie: 1109

Strona 6:
https://nofluffjobs.com/pl/devops?page=6
URL-i na stronie: 100
Nowych w kategorii: 100
Unikalnych w kategorii: 200
Łącznie globalnie: 1208

Strona 7:
https://nofluffjobs.com/pl/devops?page=7
URL-i na stronie: 112
Nowych w kategorii: 92
Unikalnych w kategorii: 292
Łącznie globalnie: 1299

Strona 8:
https://nofluffjobs.com/pl/devops?page=8
URL-i na stronie: 0
Nowych w kategorii: 0
Unikalnych w kategorii: 292
Łącznie globalnie: 1299
Brak nowych ofert w kategorii - zatrzymuję kategorię.

======================================================================
KATEGORIA: security
======================================================================

Strona 1:
https://nofluffjobs.com/pl/security?page=1
URL-i na stronie: 20
Nowych w kategorii: 20
Unikalnych w kategorii: 20
Łącznie globalnie: 1318

Strona 2:
https://nofluffjobs.com/pl/security?page=2
URL-i na stronie: 40
Nowych w kategorii: 20
Unikalnych w kategorii: 40
Łącznie globalnie: 1336

Strona 3:
https://nofluffjobs.com/pl/security?page=3
URL-i na stronie: 60
Nowych w kategorii: 20
Unikalnych w kategorii: 60
Łącznie globalnie: 1353

Strona 4:
https://nofluffjobs.com/pl/security?page=4
URL-i na stronie: 80
Nowych w kategorii: 20
Unikalnych w kategorii: 80
Łącznie globalnie: 1372

Strona 5:
https://nofluffjobs.com/pl/security?page=5
URL-i na stronie: 100
Nowych w kategorii: 20
Unikalnych w kategorii: 100
Łącznie globalnie: 1391

Strona 6:
https://nofluffjobs.com/pl/security?page=6
URL-i na stronie: 90
Nowych w kategorii: 90
Unikalnych w kategorii: 190
Łącznie globalnie: 1479

Strona 7:
https://nofluffjobs.com/pl/security?page=7
URL-i na stronie: 0
Nowych w kategorii: 0
Unikalnych w kategorii: 190
Łącznie globalnie: 1479
Brak nowych ofert w kategorii - zatrzymuję kategorię.

======================================================================
KATEGORIA: testing
======================================================================

Strona 1:
https://nofluffjobs.com/pl/testing?page=1
URL-i na stronie: 20
Nowych w kategorii: 20
Unikalnych w kategorii: 20
Łącznie globalnie: 1499

Strona 2:
https://nofluffjobs.com/pl/testing?page=2
URL-i na stronie: 40
Nowych w kategorii: 20
Unikalnych w kategorii: 40
Łącznie globalnie: 1518

Strona 3:
https://nofluffjobs.com/pl/testing?page=3
URL-i na stronie: 60
Nowych w kategorii: 20
Unikalnych w kategorii: 60
Łącznie globalnie: 1537

Strona 4:
https://nofluffjobs.com/pl/testing?page=4
URL-i na stronie: 80
Nowych w kategorii: 20
Unikalnych w kategorii: 80
Łącznie globalnie: 1557

Strona 5:
https://nofluffjobs.com/pl/testing?page=5
URL-i na stronie: 100
Nowych w kategorii: 20
Unikalnych w kategorii: 100
Łącznie globalnie: 1577

Strona 6:
https://nofluffjobs.com/pl/testing?page=6
URL-i na stronie: 100
Nowych w kategorii: 100
Unikalnych w kategorii: 200
Łącznie globalnie: 1675

Strona 7:
https://nofluffjobs.com/pl/testing?page=7
URL-i na stronie: 87
Nowych w kategorii: 67
Unikalnych w kategorii: 267
Łącznie globalnie: 1740

Strona 8:
https://nofluffjobs.com/pl/testing?page=8
URL-i na stronie: 0
Nowych w kategorii: 0
Unikalnych w kategorii: 267
Łącznie globalnie: 1740
Brak nowych ofert w kategorii - zatrzymuję kategorię.

======================================================================
KATEGORIA: java
======================================================================

Strona 1:
https://nofluffjobs.com/pl/java?page=1
URL-i na stronie: 20
Nowych w kategorii: 20
Unikalnych w kategorii: 20
Łącznie globalnie: 1740

Strona 2:
https://nofluffjobs.com/pl/java?page=2
URL-i na stronie: 40
Nowych w kategorii: 20
Unikalnych w kategorii: 40
Łącznie globalnie: 1743

Strona 3:
https://nofluffjobs.com/pl/java?page=3
URL-i na stronie: 60
Nowych w kategorii: 20
Unikalnych w kategorii: 60
Łącznie globalnie: 1744

Strona 4:
https://nofluffjobs.com/pl/java?page=4
URL-i na stronie: 80
Nowych w kategorii: 20
Unikalnych w kategorii: 80
Łącznie globalnie: 1749

Strona 5:
https://nofluffjobs.com/pl/java?page=5
URL-i na stronie: 100
Nowych w kategorii: 20
Unikalnych w kategorii: 100
Łącznie globalnie: 1752

Strona 6:
https://nofluffjobs.com/pl/java?page=6
URL-i na stronie: 100
Nowych w kategorii: 100
Unikalnych w kategorii: 200
Łącznie globalnie: 1802

Strona 7:
https://nofluffjobs.com/pl/java?page=7
URL-i na stronie: 120
Nowych w kategorii: 100
Unikalnych w kategorii: 300
Łącznie globalnie: 1836

Strona 8:
https://nofluffjobs.com/pl/java?page=8
URL-i na stronie: 120
Nowych w kategorii: 100
Unikalnych w kategorii: 400
Łącznie globalnie: 1873

Strona 9:
https://nofluffjobs.com/pl/java?page=9
URL-i na stronie: 120
Nowych w kategorii: 100
Unikalnych w kategorii: 500
Łącznie globalnie: 1909

Strona 10:
https://nofluffjobs.com/pl/java?page=10
URL-i na stronie: 120
Nowych w kategorii: 100
Unikalnych w kategorii: 600
Łącznie globalnie: 1953

Strona 11:
https://nofluffjobs.com/pl/java?page=11
URL-i na stronie: 120
Nowych w kategorii: 100
Unikalnych w kategorii: 700
Łącznie globalnie: 2002

Strona 12:
https://nofluffjobs.com/pl/java?page=12
URL-i na stronie: 51
Nowych w kategorii: 31
Unikalnych w kategorii: 731
Łącznie globalnie: 2022

Strona 13:
https://nofluffjobs.com/pl/java?page=13
URL-i na stronie: 0
Nowych w kategorii: 0
Unikalnych w kategorii: 731
Łącznie globalnie: 2022
Brak nowych ofert w kategorii - zatrzymuję kategorię.

======================================================================
KATEGORIA: .net
======================================================================

Strona 1:
https://nofluffjobs.com/pl/.net?page=1
URL-i na stronie: 20
Nowych w kategorii: 20
Unikalnych w kategorii: 20
Łącznie globalnie: 2023

Strona 2:
https://nofluffjobs.com/pl/.net?page=2
URL-i na stronie: 40
Nowych w kategorii: 20
Unikalnych w kategorii: 40
Łącznie globalnie: 2031

Strona 3:
https://nofluffjobs.com/pl/.net?page=3
URL-i na stronie: 60
Nowych w kategorii: 20
Unikalnych w kategorii: 60
Łącznie globalnie: 2037

Strona 4:
https://nofluffjobs.com/pl/.net?page=4
URL-i na stronie: 80
Nowych w kategorii: 20
Unikalnych w kategorii: 80
Łącznie globalnie: 2048

Strona 5:
https://nofluffjobs.com/pl/.net?page=5
URL-i na stronie: 100
Nowych w kategorii: 20
Unikalnych w kategorii: 100
Łącznie globalnie: 2060

Strona 6:
https://nofluffjobs.com/pl/.net?page=6
URL-i na stronie: 100
Nowych w kategorii: 100
Unikalnych w kategorii: 200
Łącznie globalnie: 2095

Strona 7:
https://nofluffjobs.com/pl/.net?page=7
URL-i na stronie: 38
Nowych w kategorii: 18
Unikalnych w kategorii: 218
Łącznie globalnie: 2107

Strona 8:
https://nofluffjobs.com/pl/.net?page=8
URL-i na stronie: 0
Nowych w kategorii: 0
Unikalnych w kategorii: 218
Łącznie globalnie: 2107
Brak nowych ofert w kategorii - zatrzymuję kategorię.

======================================================================
KATEGORIA: python
======================================================================

Strona 1:
https://nofluffjobs.com/pl/python?page=1
URL-i na stronie: 20
Nowych w kategorii: 20
Unikalnych w kategorii: 20
Łącznie globalnie: 2110

Strona 2:
https://nofluffjobs.com/pl/python?page=2
URL-i na stronie: 40
Nowych w kategorii: 20
Unikalnych w kategorii: 40
Łącznie globalnie: 2116

Strona 3:
https://nofluffjobs.com/pl/python?page=3
URL-i na stronie: 60
Nowych w kategorii: 20
Unikalnych w kategorii: 60
Łącznie globalnie: 2125

Strona 4:
https://nofluffjobs.com/pl/python?page=4
URL-i na stronie: 80
Nowych w kategorii: 20
Unikalnych w kategorii: 80
Łącznie globalnie: 2135

Strona 5:
https://nofluffjobs.com/pl/python?page=5
URL-i na stronie: 100
Nowych w kategorii: 20
Unikalnych w kategorii: 100
Łącznie globalnie: 2145

Strona 6:
https://nofluffjobs.com/pl/python?page=6
URL-i na stronie: 100
Nowych w kategorii: 100
Unikalnych w kategorii: 200
Łącznie globalnie: 2177

Strona 7:
https://nofluffjobs.com/pl/python?page=7
URL-i na stronie: 120
Nowych w kategorii: 100
Unikalnych w kategorii: 300
Łącznie globalnie: 2205

Strona 8:
https://nofluffjobs.com/pl/python?page=8
URL-i na stronie: 120
Nowych w kategorii: 100
Unikalnych w kategorii: 400
Łącznie globalnie: 2231

Strona 9:
https://nofluffjobs.com/pl/python?page=9
URL-i na stronie: 120
Nowych w kategorii: 100
Unikalnych w kategorii: 500
Łącznie globalnie: 2279

Strona 10:
https://nofluffjobs.com/pl/python?page=10
URL-i na stronie: 120
Nowych w kategorii: 100
Unikalnych w kategorii: 600

In [7]:
len(df_urls)

3286

In [8]:
from nfj import scrape_jobs

df_jobs = scrape_jobs(
    delay=1.0,
    headless=False
)

URL-i do sprawdzenia: 3286
Już pobranych: 40

======================================================================
[1/3286]
https://nofluffjobs.com/pl/job/24-7-support-entry-level-acaisoft-remote
OK: 24/7 Support – Entry Level
Company: Acaisoft
Category: Support

======================================================================
[2/3286]
https://nofluffjobs.com/pl/job/ad-operations-coordinator-emea-xperi-warszawa
OK: Ad Operations Coordinator - EMEA
Company: Xperi
Category: Product Management

======================================================================
[3/3286]
https://nofluffjobs.com/pl/job/administrator-cybersecurity-scalo-warszawa
OK: Administrator Cybersecurity
Company: Scalo
Category: Security

======================================================================
[4/3286]
https://nofluffjobs.com/pl/job/administrator-it-iteo-katowice
OK: Administrator IT
Company: iteo S.A.
Category: None

======================================================================
[5/3286]
https://nofluffjobs.com/pl/job/administrator-ka-aplikacji-biznesowych-departament-it-t-mobile-polska-warszawa
OK: Administrator/-ka Aplikacji Biznesowych - Departament IT
Company: T-Mobile Polska
Category: Support

======================================================================
[6/3286]
https://nofluffjobs.com/pl/job/administrator-ka-it-ima-polska-spolka-akcyjna-murowanagoslina
OK: Administrator/ka IT
Company: IMA POLSKA SPÓŁKA AKCYJNA
Category: None

======================================================================
[7/3286]
https://nofluffjobs.com/pl/job/administrator-sap-basis-k-m-modivo-platform-polkowice
OK: ADMINISTRATOR SAP BASIS (k/m)
Company: MODIVO PLATFORM
Category: ERP

======================================================================
[8/3286]
https://nofluffjobs.com/pl/job/administrator-systemow-linux-bsd-z-elementami-it-support-warszawa-fudo-security-warsaw
OK: Administrator Systemów Linux/BSD (z elementami IT Support) - Warszawa
Company: Fudo Security
Category: None

======================================================================
[9/3286]
https://nofluffjobs.com/pl/job/administrator-systemow-linux-unity-t-group-krakow-4
OK: Administrator Systemów Linux
Company: Unity-T Group
Category: None

======================================================================
[10/3286]
https://nofluffjobs.com/pl/job/administrator-windows-transformacja-mindbox-warszawa
OK: Administrator Windows (transformacja)
Company: Mindbox Sp. z o.o.
Category: Backend

======================================================================
[11/3286]
https://nofluffjobs.com/pl/job/adobe-analytics-specialist-it-contracting-michael-page-international
OK: Adobe Analytics Specialist - IT Contracting
Company: Michael Page
Category: Data

======================================================================
[12/3286]
https://nofluffjobs.com/pl/job/agentic-ai-technical-consultant-poland-deloitte-warsaw-1
OK: Agentic AI Technical Consultant | Poland
Company: Deloitte
Category: AI

======================================================================
[13/3286]
https://nofluffjobs.com/pl/job/agentic-ai-technical-senior-consultant-poland-deloitte-warsaw-1
OK: Agentic AI Technical Senior Consultant | Poland
Company: Deloitte
Category: AI

======================================================================
[14/3286]
https://nofluffjobs.com/pl/job/agentic-ai-technical-specialist-lead-poland-deloitte-warsaw
OK: Agentic AI Technical Specialist Lead | Poland
Company: Deloitte
Category: AI

======================================================================
[15/3286]
https://nofluffjobs.com/pl/job/agentic-platform-architect-itransition-remote
OK: Agentic Platform Architect
Company: Itransition
Category: AI

======================================================================
[16/3286]
https://nofluffjobs.com/pl/job/agile-coach-link-group-remote-3
OK: Agile Coach
Company: Link Group
Category: None

======================================================================
[17/3286]
https://nofluffjobs.com/pl/job/agile-delivery-leader-ka-one-portal-tribe-t-mobile-polska-warszawa
OK: Agile Delivery Leader/-ka - One Portal Tribe
Company: T-Mobile Polska
Category: None

======================================================================
[18/3286]
https://nofluffjobs.com/pl/job/agile-delivery-manager-link-group-remote
OK: Agile Delivery Manager
Company: Link Group
Category: Project Manager

======================================================================
[19/3286]
https://nofluffjobs.com/pl/job/ai-adoption-manager-wakacje-pl-gdansk
OK: AI Adoption Manager
Company: Wakacje.pl
Category: AI

======================================================================
[20/3286]
https://nofluffjobs.com/pl/job/ai-agent-developer-microsoft-copilot-studio-upvanta-remote
OK: AI Agent Developer (Microsoft Copilot Studio)
Company: Upvanta
Category: AI

======================================================================
[21/3286]
https://nofluffjobs.com/pl/job/ai-agent-engineer-conversational-ai-solutions-belvedere-recruitment-krakow
OK: AI Agent Engineer - Conversational AI Solutions
Company: Belvedere Recruitment
Category: Backend

======================================================================
[22/3286]
https://nofluffjobs.com/pl/job/ai-agent-engineer-mindbox-remote
OK: AI Agent Engineer
Company: Mindbox Sp. z o.o.
Category: AI

======================================================================
[23/3286]
https://nofluffjobs.com/pl/job/ai-agent-middle-senior-developer-itransition-remote
OK: AI Agent Middle/Senior Developer
Company: Itransition
Category: AI

======================================================================
[24/3286]
https://nofluffjobs.com/pl/job/ai-agents-intelligent-automation-product-lead-square-one-resources-remote
OK: AI Agents & Intelligent Automation Product Lead
Company: Square One Resources
Category: Product Management

======================================================================
[25/3286]
https://nofluffjobs.com/pl/job/ai-appsec-aisec-engineer-mindbox-krakow
OK: AI AppSec / AiSec Engineer
Company: Mindbox Sp. z o.o.
Category: AI

CHECKPOINT
Zapisano: 65

======================================================================
[26/3286]
https://nofluffjobs.com/pl/job/ai-architect-adtran-networks-remote
OK: AI Architect
Company: Adtran Networks
Category: Python, AI

======================================================================
[27/3286]
https://nofluffjobs.com/pl/job/ai-architect-square-one-resources-remote
OK: AI Architect
Company: Square One Resources
Category: AI

======================================================================
[28/3286]
https://nofluffjobs.com/pl/job/ai-architect-with-python-spyrosoft-remote
OK: AI Architect (with Python)
Company: Spyrosoft
Category: Python, AI

======================================================================
[29/3286]
https://nofluffjobs.com/pl/job/ai-automation-developer-m-f-d-argus-data-insights-germany-remote-1
OK: AI/Automation Developer (m/f/d)
Company: Argus Data Insights Germany
Category: Python, AI

======================================================================
[30/3286]
https://nofluffjobs.com/pl/job/ai-automation-engineer-microsoft-copilot-studio-spyrosoft-remote
OK: AI Automation Engineer (Microsoft Copilot Studio)
Company: Spyrosoft
Category: AI

======================================================================
[31/3286]
https://nofluffjobs.com/pl/job/ai-catalyst-lead-antal-krakow
OK: AI Catalyst Lead
Company: Antal
Category: AI

======================================================================
[32/3286]
https://nofluffjobs.com/pl/job/ai-coach-tester-antal-warszawa
OK: AI Coach - Tester
Company: Antal
Category: Testing

======================================================================
[33/3286]
https://nofluffjobs.com/pl/job/ai-coach-tester-scalo-warszawa
OK: AI Coach Tester
Company: Scalo
Category: Testing

======================================================================
[34/3286]
https://nofluffjobs.com/pl/job/ai-consultant-genai-automation-sap-environment-german-speaking-square-one-resources-remote
OK: AI Consultant (GenAI & Automation) – SAP Environment | German Speaking
Company: Square One Resources
Category: AI

======================================================================
[35/3286]
https://nofluffjobs.com/pl/job/ai-consultant-genai-spyrosoft-remote
OK: AI Consultant (GenAI)
Company: Spyrosoft
Category: AI

======================================================================
[36/3286]
https://nofluffjobs.com/pl/job/ai-content-consultant-i-deloitte-digital-i-poland-deloitte-gdansk
OK: AI Content Consultant I Deloitte Digital I Poland
Company: Deloitte
Category: AI

======================================================================
[37/3286]
https://nofluffjobs.com/pl/job/ai-data-architect-square-one-resources-remote
OK: AI Data Architect
Company: Square One Resources
Category: Architecture

======================================================================
[38/3286]
https://nofluffjobs.com/pl/job/ai-data-products-consultant-reply-polska-remote
OK: AI Data Products Consultant
Company: Reply Polska
Category: Python, AI

======================================================================
[39/3286]
https://nofluffjobs.com/pl/job/ai-data-solutions-lead-gcp-mindbox-warszawa
OK: AI & Data Solutions Lead (GCP)
Company: Mindbox Sp. z o.o.
Category: Data

======================================================================
[40/3286]
https://nofluffjobs.com/pl/job/ai-delivery-manager-verita-hr-krakow
OK: AI Delivery Manager
Company: Verita HR
Category: None

======================================================================
[41/3286]
https://nofluffjobs.com/pl/job/ai-developer-ai-developerka-avenga-agencja-pracy-nr-kraz-8448-remote
OK: AI Developer/AI Developerka
Company: AVENGA (Agencja Pracy, nr KRAZ: 8448)
Category: Python, AI

======================================================================
[42/3286]
https://nofluffjobs.com/pl/job/ai-developer-antal-warszawa-2
OK: AI Developer
Company: Antal
Category: AI

======================================================================
[43/3286]
https://nofluffjobs.com/pl/job/ai-developer-antal-warszawa-3
OK: AI Developer
Company: Antal
Category: AI

======================================================================
[44/3286]
https://nofluffjobs.com/pl/job/ai-developer-mindbox-krakow
OK: AI Developer
Company: Mindbox Sp. z o.o.
Category: AI

======================================================================
[45/3286]
https://nofluffjobs.com/pl/job/ai-developer-mindbox-krakow-2
OK: AI Developer
Company: Mindbox Sp. z o.o.
Category: Backend

======================================================================
[46/3286]
https://nofluffjobs.com/pl/job/ai-developer-moondigo-warszawa-2
OK: AI Developer
Company: Moondigo Sp. z o.o.
Category: Python, AI

======================================================================
[47/3286]
https://nofluffjobs.com/pl/job/ai-developer-verita-hr-krakow
OK: AI Developer
Company: Verita HR
Category: Python, AI

======================================================================
[48/3286]
https://nofluffjobs.com/pl/job/ai-devops-engineer-lingaro-remote-4
OK: AI DevOps Engineer
Company: Lingaro
Category: Python, DevOps

======================================================================
[49/3286]
https://nofluffjobs.com/pl/job/ai-enablement-lead-travelplanet-pl-invia-group-wroclaw
OK: AI Enablement Lead
Company: Travelplanet.pl SA (Invia Group)
Category: AI

======================================================================
[50/3286]
https://nofluffjobs.com/pl/job/ai-enablement-lead-wakacje-pl-gdansk
OK: AI Enablement Lead
Company: Wakacje.pl
Category: AI

CHECKPOINT
Zapisano: 90

======================================================================
[51/3286]
https://nofluffjobs.com/pl/job/ai-enablement-specialist-german-speaking-enterprise-sap-transformation-polcode-remote
OK: AI Enablement Specialist (German-speaking) | Enterprise SAP Transformation
Company: Polcode
Category: ERP

======================================================================
[52/3286]
https://nofluffjobs.com/pl/job/ai-engineer-100-remote-ds-stream-1
OK: AI Engineer 100% REMOTE
Company: DS STREAM
Category: Python, AI

======================================================================
[53/3286]
https://nofluffjobs.com/pl/job/ai-engineer-clouds-on-mars-remote-3
OK: AI Engineer
Company: Clouds on Mars Sp. z o.o.
Category: AI

======================================================================
[54/3286]
https://nofluffjobs.com/pl/job/ai-engineer-dcg-remote
OK: AI Engineer
Company: DCG
Category: AI

======================================================================
[55/3286]
https://nofluffjobs.com/pl/job/ai-engineer-dcg-warszawa-3
OK: AI Engineer
Company: DCG
Category: AI

======================================================================
[56/3286]
https://nofluffjobs.com/pl/job/ai-engineer-ework-group-gdansk
OK: AI Engineer
Company: Ework Group
Category: Python, AI

======================================================================
[57/3286]
https://nofluffjobs.com/pl/job/ai-engineer-generative-ai-solutions-belvedere-recruitment-warsaw
OK: AI Engineer - Generative AI Solutions
Company: Belvedere Recruitment
Category: AI

======================================================================
[58/3286]
https://nofluffjobs.com/pl/job/ai-engineer-it-contracting-michael-page-warsaw
OK: AI Engineer - IT Contracting
Company: Michael Page
Category: AI

======================================================================
[59/3286]
https://nofluffjobs.com/pl/job/ai-engineer-itfs-warszawa-4
OK: AI Engineer
Company: ITFS Sp. z o.o.
Category: Python, AI

======================================================================
[60/3286]
https://nofluffjobs.com/pl/job/ai-engineer-link-group-remote-7
OK: AI Engineer
Company: Link Group
Category: Python, AI

======================================================================
[61/3286]
https://nofluffjobs.com/pl/job/ai-engineer-llms-python-addepto-remote-12
OK: AI Engineer (LLMs, Python)
Company: Addepto
Category: Python, AI

======================================================================
[62/3286]
https://nofluffjobs.com/pl/job/ai-engineer-michael-page-remote
OK: AI Engineer
Company: Michael Page
Category: AI

======================================================================
[63/3286]
https://nofluffjobs.com/pl/job/ai-engineer-nextgen-t-mobile-polska-warszawa-1
OK: AI Engineer - NextGen
Company: T-Mobile Polska
Category: AI

======================================================================
[64/3286]
https://nofluffjobs.com/pl/job/ai-engineer-ochk-remote
OK: AI Engineer
Company: OChK
Category: AI

======================================================================
[65/3286]
https://nofluffjobs.com/pl/job/ai-engineer-scalo-warszawa-3
OK: AI Engineer
Company: Scalo
Category: AI

======================================================================
[66/3286]
https://nofluffjobs.com/pl/job/ai-engineer-senior-scalo-warszawa-2
OK: AI Engineer (Senior)
Company: Scalo
Category: AI

======================================================================
[67/3286]
https://nofluffjobs.com/pl/job/ai-engineer-synechron-krakow
OK: AI Engineer
Company: Synechron
Category: Python, AI

======================================================================
[68/3286]
https://nofluffjobs.com/pl/job/ai-expert-in-finance-risk-capgemini-invent-krakow-1
OK: AI Expert in Finance & Risk
Company: Capgemini Invent
Category: AI

======================================================================
[69/3286]
https://nofluffjobs.com/pl/job/ai-first-full-stack-engineer-matrix-global-services-remote
OK: AI-First Full Stack Engineer
Company: Matrix Global Services
Category: Java, Fullstack

======================================================================
[70/3286]
https://nofluffjobs.com/pl/job/ai-fullstack-engineer-antal-krakow
OK: AI Fullstack Engineer
Company: Antal
Category: Fullstack

======================================================================
[71/3286]
https://nofluffjobs.com/pl/job/ai-governance-engineer-microsoft-365-copilot-verita-hr-remote-1
OK: AI Governance Engineer (Microsoft 365 / Copilot)
Company: Verita HR
Category: AI

======================================================================
[72/3286]
https://nofluffjobs.com/pl/job/ai-implementation-project-management-specialist-ewt-truck-trailer-polska-oltarzew
OK: AI Implementation & Project Management Specialist
Company: EWT Truck & Trailer Polska Sp. zo.o.
Category: AI

======================================================================
[73/3286]
https://nofluffjobs.com/pl/job/ai-ml-engineer-connectis--remote-10
OK: AI/ML Engineer
Company: Connectis_
Category: AI

======================================================================
[74/3286]
https://nofluffjobs.com/pl/job/ai-ml-engineer-lingaro-remote-2
OK: AI/ML Engineer
Company: Lingaro
Category: Python, AI

======================================================================
[75/3286]
https://nofluffjobs.com/pl/job/ai-ml-engineer-lingaro-remote-3
OK: AI/ML Engineer
Company: Lingaro
Category: Python, AI

CHECKPOINT
Zapisano: 115

======================================================================
[76/3286]
https://nofluffjobs.com/pl/job/ai-ml-engineer-mindbox-remote
OK: AI/ML Engineer
Company: Mindbox Sp. z o.o.
Category: AI

======================================================================
[77/3286]
https://nofluffjobs.com/pl/job/ai-ml-engineer-spyrosoft-wroclaw
OK: AI/ML Engineer
Company: Spyrosoft
Category: AI

======================================================================
[78/3286]
https://nofluffjobs.com/pl/job/ai-ml-engineer-virtusa-remote
OK: AI / ML Engineer
Company: VIRTUSA
Category: Python, AI

======================================================================
[79/3286]
https://nofluffjobs.com/pl/job/ai-mlops-engineer-dcg-warszawa
OK: AI/ MLOps Engineer
Company: DCG
Category: AI

======================================================================
[80/3286]
https://nofluffjobs.com/pl/job/ai-native-backend-developer-devire-remote
OK: AI Native Backend Developer
Company: Devire
Category: Backend

======================================================================
[81/3286]
https://nofluffjobs.com/pl/job/ai-native-backend-developer-michael-page-remote
OK: AI Native Backend Developer
Company: Michael Page
Category: Backend

======================================================================
[82/3286]
https://nofluffjobs.com/pl/job/ai-native-mid-fullstack-developer-meant4-software-remote
OK: AI‑Native Mid Fullstack Developer
Company: Meant4 Software
Category: Fullstack

======================================================================
[83/3286]
https://nofluffjobs.com/pl/job/ai-product-manager-link-group-remote-1
OK: AI Product Manager
Company: Link Group
Category: Product Management

======================================================================
[84/3286]
https://nofluffjobs.com/pl/job/ai-production-process-engineer-it-contracting-michael-page-remote
OK: AI Production Process Engineer - IT Contracting
Company: Michael Page
Category: Backend

======================================================================
[85/3286]
https://nofluffjobs.com/pl/job/ai-project-manager-verita-hr-krakow-1
OK: AI Project Manager
Company: Verita HR
Category: Project Manager

======================================================================
[86/3286]
https://nofluffjobs.com/pl/job/ai-researcher-semiconductor-materials-ai-shenzhen-residency-tcl-research-europe-shenzhen
OK: AI Researcher – Semiconductor & Materials AI (Shenzhen Residency)
Company: TCL Research Europe Sp. z o.o.
Category: Python, AI

======================================================================
[87/3286]

In [9]:
import pandas as pd
from nfj.config import URLS_PATH, OUTPUT_PATH

df_urls = pd.read_csv(URLS_PATH)
df_jobs = pd.read_csv(OUTPUT_PATH)

print("URL-e:", len(df_urls))
print("Unikalne URL-e:", df_urls["url"].nunique())

print()
print("Oferty:", len(df_jobs))
print("Unikalne oferty:", df_jobs["url"].nunique())

print()
print(
    "Brakujące URL-e:",
    len(
        set(df_urls["url"])
        - set(df_jobs["url"])
    )
)

URL-e: 3286
Unikalne URL-e: 3286

Oferty: 3286
Unikalne oferty: 3286

Brakujące URL-e: 0